//! Agent core: orchestrates LLM calls, tool execution, streaming,
//! context window management, and operation confirmation.

mod interrupt;
mod confirmation;
mod plan_mode;
mod tool_loop;

pub use interrupt::{clear_guidance, clear_interrupt, is_interrupted, request_guidance, request_interrupt};
pub(crate) use interrupt::register_session_interrupt;
pub(crate) use tool_loop::ToolLoopOptions;

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::Result;

use crate::config::{Config, Provider};
use crate::context;
use crate::conversation::{ContentBlock, Conversation, Message, Role};
use crate::memory::MemoryProvider;
use crate::model_manager;
use crate::output::{AgentOutput, SilentOutput};
use crate::path_manager;
use crate::sandbox::Sandbox;
use crate::service::{ServiceEvent, SERVICE_EVENT_TX};
use crate::streaming;
use crate::tools::ToolExecutor;

/// The main Agent that orchestrates LLM calls and tool execution
pub struct Agent {
    pub config: Config,
    pub project_dir: PathBuf,
    pub(crate) tool_executor: ToolExecutor,
    pub conversation: Conversation,
    pub memory: Arc<dyn MemoryProvider>,
    total_input_tokens: u64,
    total_output_tokens: u64,
    /// Per-role token usage: maps role name → (input_tokens, output_tokens).
    /// Tracks cost breakdown across router, planner, executor, checker, agent, summary, etc.
    role_token_usage: HashMap<String, (u64, u64)>,
    pub(crate) session_id: Option<String>,
    pub(crate) output: Arc<dyn AgentOutput>,
    /// Holds a pending plan generated by `generate_plan()`, ready for `execute_plan()`.
    pub pending_plan: Option<String>,
    /// Plan-mode session state. When true the model sees only read-only tools plus
    /// exit_plan_mode, and must get an approved plan before implementing.
    pub plan_mode: bool,
    /// Delegation depth of this agent (0 = top-level). Bounds recursive sub-agent
    /// spawning so the model cannot spawn an unbounded chain.
    pub delegation_depth: usize,
    /// Live continuable sub-agent sessions, keyed by a sub-agent id. The model can
    /// follow up an existing sub-agent (subagent_followup) rather than only making
    /// one-shot spawns.
    pub subagents: Arc<tokio::sync::Mutex<HashMap<String, Arc<tokio::sync::Mutex<Agent>>>>>,
    /// Maximum sub-agent nesting depth before spawns are refused.
    pub max_subagent_depth: usize,
    /// Maximum number of concurrently live sub-agent sessions per agent.
    pub max_subagents: usize,
    /// Loaded models.toml config, kept for role resolution at runtime.
    pub models_cfg: model_manager::ModelsConfig,
    /// Per-role Config cache, built once on construction.
    /// Key is role name (e.g. "planner", "executor", "checker").
    pub(crate) role_configs: HashMap<String, Config>,
    /// Sandbox for snapshot-based rollback.
    pub sandbox: Sandbox,
    /// Path manager for unified path handling.
    pub path_manager: Arc<path_manager::PathManager>,
    /// When false (default), sessions are stored in the project's `.agent/session.json`.
    /// When true, sessions are stored in the global `~/.local/share/rust_agent/sessions/`.
    pub global_session: bool,
    /// Receiver for push notifications from external services.
    /// Drained at safe points (between tool iterations) and displayed via
    /// `AgentOutput::on_service_notification`.
    service_events: tokio::sync::broadcast::Receiver<ServiceEvent>,
    /// When set, overrides the adaptive router for every message.
    /// `None` means use the normal router logic.
    pub force_mode: Option<crate::router::ExecutionMode>,

    /// Plugin manager for plugin system integration
    pub plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>,
    /// Hook 事件总线（与 PluginManager 共享同一 Arc）
    pub(crate) hook_bus: Option<Arc<crate::plugin::hook_bus::HookBus>>,
    /// Number of completed message turns. Used to trigger periodic knowledge extraction.
    knowledge_extract_turns: u32,
    /// Total completed turns since agent was created. Passed to memory provider hooks.
    total_turns: u64,
    /// Per-session interrupt flag. Set by Ctrl-C handler or WebSocket "cancel"
    /// message. Checked between tool iterations so the agent can stop cleanly
    /// without leaving the conversation in an invalid state.
    pub(crate) interrupt_requested: Arc<AtomicBool>,
    // ── Loop detection / guardrail fields ────────────────────────────────
    /// Hash history of tool calls within the current turn
    /// (tool_name, args_hash) → how many times it's been repeated.
    pub(crate) turn_tool_call_hashes: HashMap<(String, u64), u32>,
    /// Number of consecutive turns with zero file mutations
    /// (write_file, edit_file, multi_edit_file).  Reset on mutation.
    pub(crate) turns_without_mutation: u32,
    /// Number of consecutive turns where the LLM produced identical tool calls.
    pub(crate) identical_tool_turns: u32,
    /// Snapshot of the previous turn's tool call hashes for cross-turn comparison.
    pub(crate) prev_turn_hashes: HashMap<(String, u64), u32>,
    /// Pluggable context engine for token estimation, truncation, and summarization.
    /// Defaults to `DefaultContextEngine`; can be swapped for custom strategies.
    pub context_engine: Box<dyn context::ContextEngine>,
}

impl Agent {
    /// Enable or disable sandbox mode dynamically
    pub fn set_sandbox_enabled(&mut self, enabled: bool) {
        if enabled && self.sandbox.working_dir() == &self.project_dir {
            // 如果沙盒当前是禁用的，尝试启用它
            let sandbox = crate::sandbox::Sandbox::new(&self.project_dir);
            self.sandbox = sandbox;
            // 更新 path manager
            let new_path_manager = Arc::new(path_manager::PathManager::with_sandbox(
                self.project_dir.clone(),
                Arc::new(self.sandbox.clone()),
            ));
            self.path_manager = new_path_manager.clone();
            // 更新工具执行器
            self.tool_executor.set_path_manager(new_path_manager);

            // 仅当 overlay 实际挂载成功（sandbox 不再是 disabled）时才注入系统提示词。
            // 如果 fuse-overlayfs 不可用，sandbox 静默回退为 disabled，此时绝对不能
            // 向 LLM 声称"处于沙盒隔离中"，否则 LLM 会误以为 rm -rf 等操作无害。
            if !self.sandbox.is_disabled {
                let sandbox_note = "\n\n## Sandbox Mode\n\
                - You are running in **sandbox mode** (overlay filesystem).\n\
                - All file operations are isolated in the sandbox directory.\n\
                - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
                - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
                - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
                if !self.conversation.system_prompt.contains("## Sandbox Mode") {
                    self.conversation.system_prompt.push_str(sandbox_note);
                }
            } else {
                // Overlay 不可用，记录警告（CLI 侧会通过 backend_label_sync 展示给用户）
                tracing::warn!("sandbox: fuse-overlayfs unavailable — sandbox disabled, NOT injecting sandbox system prompt");
            }
        } else if !enabled && self.sandbox.working_dir() != &self.project_dir {
            // 如果沙盒当前是启用的，禁用它
            self.sandbox = crate::sandbox::Sandbox::disabled(&self.project_dir);
            // 更新 path manager
            let new_path_manager = Arc::new(path_manager::PathManager::without_sandbox(
                self.project_dir.clone(),
            ));
            self.path_manager = new_path_manager.clone();
            // 更新工具执行器
            self.tool_executor.set_path_manager(new_path_manager);
            
            // 移除沙盒模式说明
            if let Some(start) = self.conversation.system_prompt.find("## Sandbox Mode") {
                if let Some(end) = self.conversation.system_prompt[start..].find("\n\n## ") {
                    self.conversation.system_prompt.replace_range(start..start+end, "");
                } else {
                    // 如果沙盒说明在末尾，直接截断
                    self.conversation.system_prompt.truncate(start);
                }
            }
        }
    }

    /// Update both `project_dir` and the tool executor's working directory.
    pub fn set_project_dir(&mut self, dir: PathBuf) {
        self.project_dir = dir.clone();
        self.tool_executor.set_project_dir(dir);
    }

    /// Restrict write/edit tools to paths inside `dir` for this agent.
    /// Pass `None` to remove the restriction.
    pub fn set_allowed_dir(&mut self, dir: Option<std::path::PathBuf>) {
        self.tool_executor.set_allowed_dir(dir.clone());
        // Also update path manager by creating a new one
        if let Some(path_manager) = Arc::get_mut(&mut self.path_manager) {
            path_manager.set_allowed_dir(dir);
        }
    }
    
    /// Load plugin tools from plugin manager
    pub async fn load_plugin_tools(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        self.tool_executor.load_plugin_tools().await
    }

    /// Connect to the supplied MCP server entries and register their tools.
    /// Used by server/worker mode where the client sends a `load_mcp` message.
    /// Returns `(loaded_tool_names, error_strings)`.
    pub async fn load_mcp_from_entries(
        &mut self,
        entries: &[crate::mcp_client::McpServerEntry],
    ) -> (Vec<String>, Vec<String>) {
        self.tool_executor.load_mcp_from_entries(entries).await
    }

    /// Unload all tools belonging to the MCP server identified by `prefix`.
    /// Returns the names of the removed tools.
    pub fn unload_mcp(&mut self, prefix: &str) -> Vec<String> {
        self.tool_executor.unload_mcp_by_prefix(prefix)
    }

    /// Return `(name, description)` pairs for all currently-loaded MCP tools.
    pub fn list_mcp_tools(&self) -> Vec<(String, String)> {
        self.tool_executor.list_mcp_tools()
    }

    // ── Per-session interrupt methods ───────────────────────────────────
    /// Request interruption of this specific agent session.
    pub fn request_interrupt(&self) {
        self.interrupt_requested.store(true, Ordering::Relaxed);
    }

    /// Check whether an interrupt has been requested for this session.
    pub fn is_interrupted(&self) -> bool {
        self.interrupt_requested.load(Ordering::Relaxed)
    }

    pub fn new(config: Config, project_dir: PathBuf, output: Arc<dyn AgentOutput>, sandbox: Sandbox, plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>) -> Self {
        let memory: Arc<dyn MemoryProvider> =
            crate::memory::create_memory_provider(&config.memory, &project_dir);
        let mut conversation = Conversation::new(&project_dir);
        conversation.push_memory_knowledge(&memory.recall());
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        
        // Create path manager
        let path_manager = Arc::new(path_manager::PathManager::with_sandbox(
            project_dir.clone(),
            Arc::new(sandbox.clone()),
        ));
        
        // Per-session interrupt flag — registered in the global registry so
        // Ctrl-C / WebSocket "cancel" can interrupt this session.
        let interrupt_requested = Arc::new(AtomicBool::new(false));
        register_session_interrupt(&interrupt_requested);
        
        let mut agent = Agent {
            config,
            tool_executor: ToolExecutor::new(effective_dir, plugin_manager.clone()),
            conversation,
            memory: memory.clone(),
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: None,
            output,
            project_dir,
            pending_plan: None,
            plan_mode: false,
            delegation_depth: 0,
            subagents: Arc::new(tokio::sync::Mutex::new(HashMap::new())),
            max_subagent_depth: 3,
            max_subagents: 8,
            models_cfg,
            role_configs,
            sandbox,
            path_manager,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,

            plugin_manager,
            hook_bus: None,
            knowledge_extract_turns: 0,
            total_turns: 0,
            interrupt_requested,
            turn_tool_call_hashes: HashMap::new(),
            turns_without_mutation: 0,
            identical_tool_turns: 0,
            prev_turn_hashes: HashMap::new(),
            context_engine: Box::new(context::DefaultContextEngine),
        };
        
        // Set path manager in tool executor
        agent.tool_executor.set_path_manager(agent.path_manager.clone());
        
        // Register memory tool so the LLM can manage its own memory
        agent.tool_executor.register_memory_tool(memory);

        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Create agent with a restored conversation
    pub fn with_conversation(config: Config, project_dir: PathBuf, conversation: Conversation, session_id: String, output: Arc<dyn AgentOutput>, sandbox: Sandbox, plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>) -> Self {
        // Restored sessions must use the same configured backend as `new()`:
        // hard-coding a backend here used to silently drop memory writes.
        let memory: Arc<dyn MemoryProvider> =
            crate::memory::create_memory_provider(&config.memory, &project_dir);
        let conv_depth = conversation.delegation_depth;
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        // Create path manager
        let path_manager = Arc::new(path_manager::PathManager::with_sandbox(
            project_dir.clone(),
            Arc::new(sandbox.clone()),
        ));
        
        // Per-session interrupt flag
        let interrupt_requested = Arc::new(AtomicBool::new(false));
        register_session_interrupt(&interrupt_requested);
        
        let mut agent = Agent {
            config,
            tool_executor: ToolExecutor::new(effective_dir, plugin_manager.clone()),
            conversation,
            memory: memory.clone(),
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: Some(session_id),
            output,
            project_dir,
            pending_plan: None,
            plan_mode: false,
            delegation_depth: conv_depth,
            subagents: Arc::new(tokio::sync::Mutex::new(HashMap::new())),
            max_subagent_depth: 3,
            max_subagents: 8,
            models_cfg,
            role_configs,
            sandbox,
            path_manager,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,

            plugin_manager,
            hook_bus: None,
            knowledge_extract_turns: 0,
            total_turns: 0,
            interrupt_requested,
            turn_tool_call_hashes: HashMap::new(),
            turns_without_mutation: 0,
            identical_tool_turns: 0,
            prev_turn_hashes: HashMap::new(),
            context_engine: Box::new(context::DefaultContextEngine),
        };
        
        // Set path manager in tool executor
        agent.tool_executor.set_path_manager(agent.path_manager.clone());
        
        // Register memory tool so the LLM can manage its own memory
        agent.tool_executor.register_memory_tool(memory);
        

        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Get or create a session ID for persistence
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Set session ID and notify memory providers of the switch.
    pub fn set_session_id(&mut self, id: String) {
        let old_id = self.session_id.take();
        let old_str = old_id.as_deref().unwrap_or("");
        self.session_id = Some(id.clone());
        self.tool_executor.set_session_id(self.session_id.clone());
        self.memory.on_session_switch(&id, old_str, false);
    }

    /// 设置 Hook 事件总线共享引用。
    /// 由 cli.rs 在 load_all_plugins 完成后调用，同时也将 hook_bus 传递给内部的 ToolExecutor。
    pub fn set_hook_bus(&mut self, bus: Option<Arc<crate::plugin::hook_bus::HookBus>>) {
        self.tool_executor.set_hook_bus(bus.clone());
        self.tool_executor.set_session_id(self.session_id.clone());
        self.hook_bus = bus;
    }

    /// Switch the active model at runtime.
    pub fn switch_model(&mut self, resolved: &crate::model_manager::ResolvedModel) {
        self.config = self.config.with_resolved_model(resolved);
    }

    /// Drain all pending service push events and display them via
    /// `AgentOutput::on_service_notification`.
    ///
    /// Called at **safe points** — between tool iterations in the main loop
    /// and between REPL prompts in cli.rs — so notifications never interrupt
    /// LLM streaming mid-token.
    pub(crate) fn drain_service_events(&mut self) {
        use tokio::sync::broadcast::error::TryRecvError;
        loop {
            match self.service_events.try_recv() {
                Ok(ev) => {
                    self.output.on_service_notification(&ev.source, ev.level, &ev.message);
                }
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Lagged(n)) => {
                    self.output.on_service_notification(
                        "system",
                        crate::output::NotifyLevel::Warning,
                        &format!("Dropped {} service notifications (channel lagged)", n),
                    );
                }
                Err(TryRecvError::Closed) => break,
            }
        }
    }

    /// Maximum number of retries for transient LLM API errors.
    const LLM_MAX_RETRIES: u32 = 3;

    /// Check whether an error message indicates a transient/recoverable failure.
    pub(crate) fn is_transient_error(err_msg: &str) -> bool {
        let lower = err_msg.to_lowercase();
        lower.contains("dns error")
            || lower.contains("connection reset")
            || lower.contains("connection refused")
            || lower.contains("timed out")
            || lower.contains("timeout")
            || lower.contains("broken pipe")
            || lower.contains("try again")
            || lower.contains("temporarily unavailable")
            || lower.contains("eof before")
            || lower.contains("connection closed")
            || lower.contains("connection aborted")
            || lower.contains("network unreachable")
            || lower.contains("host unreachable")
            || lower.contains("error sending request")
            || lower.contains("failed to send")
            || lower.contains("failed to lookup address")
            || lower.contains("api error (429)")
            || lower.contains("api error (500)")
            || lower.contains("api error (502)")
            || lower.contains("api error (503)")
            || lower.contains("api error (504)")
            || lower.contains("overloaded")
    }

    /// Call the LLM using the config for a specific role.
    ///
    /// Falls back to `self.config` when the role is not configured.
    /// Emits an info-level UI note showing which model is active.
    pub(crate) async fn call_llm_as_role(
        &self,
        role: &str,
        conversation: &Conversation,
        tools: &[crate::tools::ToolDefinition],
    ) -> Result<crate::llm::LlmResponse> {
        let role_cfg = self.role_configs.get(role);
        let cfg = role_cfg.unwrap_or(&self.config);
        let role_label = match role {
            "planner"    => "🧠 Planner",
            "executor"   => "⚙️  Executor",
            "checker"    => "🔍 Checker",
            "router"     => "🔀 Router",
            "summarizer" => "📝 Summarizer",
            "agent"      => "🤖 Agent",
            other        => other,
        };
        // Show the role/model banner before a response.
        let model_name = cfg.model_alias.as_deref().unwrap_or(&cfg.model).to_string();
        self.output.on_role_header(role_label, &model_name);
        self.output.on_thinking();

        let mut last_err = None;
        for attempt in 0..=Self::LLM_MAX_RETRIES {
            let result = match cfg.provider {
                Provider::Anthropic => {
                    streaming::stream_anthropic_response(cfg, conversation, tools, &*self.output).await
                }
                Provider::OpenAI | Provider::Compatible => {
                    streaming::stream_openai_response(cfg, conversation, tools, &*self.output).await
                }
            };
            match result {
                Ok(response) => return Ok(response),
                Err(e) => {
                    // {:#} prints the ANYHOW cause chain, so a transport failure
                    // (DNS / proxy / TLS / connect timeout) is visible instead of
                    // just the generic "Failed to send streaming request" context.
                    let err_msg = format!("{:#}", e);
                    if Self::is_transient_error(&err_msg) && attempt < Self::LLM_MAX_RETRIES {
                        let delay = 2u64.pow(attempt + 1);
                        self.output.on_warning(&format!(
                            "API request failed (attempt {}/{}): {}. Retrying in {}s...",
                            attempt + 1, Self::LLM_MAX_RETRIES + 1, err_msg, delay
                        ));
                        tokio::time::sleep(std::time::Duration::from_secs(delay)).await;
                        last_err = Some(e);
                    } else {
                        return Err(e);
                    }
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow::anyhow!("LLM request failed after retries")))
    }

    /// Run one LLM call with no user-visible output.
    ///
    /// Used for background work — truncation summarization, knowledge
    /// extraction, memory consolidation — that must not interleave with the
    /// interactive transcript.
    async fn call_llm_silent(
        &self,
        cfg: &Config,
        conversation: &Conversation,
        tools: &[crate::tools::ToolDefinition],
    ) -> Result<crate::llm::LlmResponse> {
        let silent = SilentOutput;
        match cfg.provider {
            Provider::Anthropic => {
                streaming::stream_anthropic_response(cfg, conversation, tools, &silent).await
            }
            Provider::OpenAI | Provider::Compatible => {
                streaming::stream_openai_response(cfg, conversation, tools, &silent).await
            }
        }
    }

    /// Override the adaptive router for all subsequent messages.
    /// Pass `None` to restore normal router behaviour.
    pub fn set_force_mode(&mut self, mode: Option<crate::router::ExecutionMode>) {
        self.force_mode = mode;
    }

    /// Determine the execution mode for a given user message.
    ///
    /// If `force_mode` is set it takes priority over everything else.
    /// Otherwise the always-basic-loop default is used.
    pub async fn resolve_execution_mode(
        &self,
        _user_input: &str,
    ) -> crate::router::ExecutionMode {
        // The router is retired: the model drives plan-mode (plan_mode
        // flag) and delegation (call_node). Honor an explicit force_mode (e.g.
        // /mode) for command compatibility, otherwise always run the basic loop.
        if let Some(forced) = self.force_mode {
            return forced;
        }
        crate::router::ExecutionMode::BasicLoop
    }

    /// Enter or leave plan mode. While on, the model sees only read-only tools
    /// plus exit_plan_mode; an approved plan is required before it can act.
    pub fn set_plan_mode(&mut self, on: bool) {
        self.plan_mode = on;
    }


    /// 发射 `router.decision` intercepting hook，允许插件覆盖路由模式。
    /// 脚本失败/超时均回退为原模式，不阻断主流程。
    async fn apply_router_hook(
        &self,
        mode: crate::router::ExecutionMode,
        user_input: &str,
    ) -> crate::router::ExecutionMode {
        use crate::router::ExecutionMode;
        use crate::plugin::hook_bus::{HookEvent, HookResult};

        let bus = match &self.hook_bus {
            Some(b) => b.clone(),
            None => return mode,
        };

        let mode_str = match mode {
            ExecutionMode::BasicLoop => "basic_loop",
        };
        let classification_source = if self.force_mode.is_some() { "forced" } else { "auto" };
        let task_preview: String = user_input.chars().take(200).collect();

        let event = HookEvent::new(
            "router.decision",
            self.session_id.as_deref().unwrap_or("none").to_string(),
            serde_json::json!({
                "proposed_mode":        mode_str,
                "classification_source": classification_source,
                "task_preview":          task_preview,
            }),
        );

        match bus.emit_intercepting(event).await {
            HookResult::PatchParams { params } => {
                let override_str = params
                    .get("override_mode")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let new_mode = match override_str {
                    "basic_loop" => ExecutionMode::BasicLoop,
                    other => {
                        self.output.on_warning(&format!(
                            "[hook] router.decision: unknown override_mode '{}', keeping '{}'",
                            other, mode_str
                        ));
                        return mode;
                    }
                };
                if new_mode != mode {
                    let new_str = match new_mode {
                        ExecutionMode::BasicLoop => "basic_loop",
                    };
                    self.output.on_warning(&format!(
                        "🔀 Router overridden by hook: {} → {}",
                        mode_str, new_str
                    ));
                }
                new_mode
            }
            // Cancel / Approved 不阻断路由，降级为原决策
            HookResult::Cancel { reason } => {
                self.output.on_warning(&format!(
                    "[hook] router.decision cancelled ({}), keeping '{}'",
                    reason, mode_str
                ));
                mode
            }
            HookResult::Approved { .. } | HookResult::Continue => mode,
        }
    }

    /// Generate a brief explanation of what a tool is about to do and answer
    /// the user's question. Uses a lightweight LLM call (no tools).

    /// Query the hook system to see if a confirmation should be auto-approved,
    /// auto-denied, or left to the normal UI flow.
    ///
    /// Returns:
    ///   `Some(true)`  — hook approved; skip UI prompt
    ///   `Some(false)` — hook denied;   skip UI prompt
    ///   `None`        — no hook verdict; fall through to normal UI

    // ── Unified tool loop ─────────────────────────────────────────────────

    /// The unified tool loop that powers `process_message`.
    ///
    /// Each caller selects the subset of features via `opts` while the core
    /// LLM→tools→results→context cycle is shared.

    /// Process a user message and return the final text response.
    /// This handles the full agent loop: send message → receive response →
    /// if tool use → execute tools → send results → repeat until done.
    pub async fn process_message(&mut self, user_input: &str) -> Result<String> {
        // ── Router decision hook ─────────────────────────────────────────
        // Emit the (retired) router.decision hook so plugins can still observe
        // / override the mode, then fall through to the basic loop. Only
        // basic_loop is meaningful now; planning is driven by plan_mode.
        let mode = self.resolve_execution_mode(user_input).await;
        let _ = self.apply_router_hook(mode, user_input).await;

        let mut enriched_input = user_input.to_string();


        // ── Sync global interrupt to per-session flag ─────────────────────
        // If a Ctrl-C happened before this turn started, propagate it to our
        // session flag and clear the global so we don't see it again next time.
        if is_interrupted() {
            self.request_interrupt();
            clear_interrupt();
        }

        // ── Reset loop detection counters for new turn ──────────────────
        self.turn_tool_call_hashes.clear();
        self.turns_without_mutation = 0;
        // Note: identical_tool_turns and prev_turn_hashes are NOT reset here
        // — they track patterns *across* turns, not within a single turn.

        // ── Turn start: notify memory providers ─────────────────────────
        self.total_turns += 1;
        self.conversation.append_turn_start(self.total_turns as u64);
        let max_tokens = self.context_engine.max_context_tokens(&self.config.model);
        let used_tokens = context::estimate_conversation_tokens(&self.conversation);
        let remaining_tokens = max_tokens.saturating_sub(used_tokens) as u64;
        self.memory.on_turn_start(
            self.total_turns as u32,
            user_input,
            remaining_tokens,
            &self.config.model,
        );

        if self.plan_mode {
            enriched_input = format!(
                "{}

[PLAN MODE GUIDANCE]
{}",
                plan_mode::plan_mode_guidance(),
                enriched_input
            );
        }

        // Add (already enriched) user message
        self.conversation.add_message(Message::user(&enriched_input));

        // Check context window before sending
        self.check_and_manage_context().await;

        let tool_defs = if self.plan_mode {
            confirmation::with_ask_user(
                plan_mode::plan_mode_toolset(self.tool_executor.readonly_definitions()),
            )
        } else {
            let mut defs = confirmation::with_ask_user(self.tool_executor.definitions());
            defs.push(plan_mode::subagent_definition());
            defs.push(plan_mode::subagent_fork_definition());
            defs.push(plan_mode::subagent_followup_definition());
            defs.push(plan_mode::subagent_terminate_definition());
            defs
        };

        let opts = ToolLoopOptions {
            role: "agent".to_string(),
            enable_guardrails: true,
            enable_guidance: false,
            notify_file_created: true,
            handle_upload_image: true,
        };

        // Temporarily take ownership of the conversation so we can pass
        // a `&mut Conversation` to `run_tool_loop` without conflicting with
        // the `&mut self` borrow also required by that method.
        let placeholder = self.fresh_conversation();
        let mut conversation = std::mem::replace(&mut self.conversation, placeholder);
        let mut final_text = self
            .run_tool_loop(&mut conversation, &tool_defs, &opts)
            .await?;
        self.conversation = conversation;
        self.conversation.append_turn_end(self.total_turns as u64);
        if !self.conversation.log_is_consistent() {
            tracing::warn!(
                "[phase4] turn {} ended with a session log that diverged from the message surface;                  the log is authoritative and will be used on persistence",
                self.total_turns
            );
        }

        // If run_tool_loop returned empty (e.g. loop exhausted), fall back to
        // scanning the conversation for the last assistant text.
        if final_text.is_empty() {
            final_text = self
                .conversation
                .messages
                .iter()
                .rev()
                .find(|m| m.role == crate::conversation::Role::Assistant)
                .map(|m| m.text_content())
                .unwrap_or_default();
        }

        // Periodic knowledge extraction, every `extraction_frequency` turns.
        self.knowledge_extract_turns += 1;
        let extract_every = self.config.memory.extraction_frequency.max(1) as u32;
        if self.knowledge_extract_turns % extract_every == 0 {
            self.extract_and_store_knowledge().await;
        }

        // Periodic diagnostics: every 10 turns, log conversation stats so we
        // can correlate hook-script timeouts with memory / context growth.
        if self.knowledge_extract_turns % 10 == 0 {
            let msg_count = self.conversation.messages.len();
            let token_est = context::estimate_conversation_tokens(&self.conversation);
            let mem_est: usize = self.conversation.messages.iter()
                .map(|m| m.content.iter().map(|b| match b {
                    ContentBlock::Text { text } => text.len(),
                    ContentBlock::ToolResult { content, .. } => content.len(),
                    ContentBlock::Thinking { thinking, .. } => thinking.len(),
                    _ => 256,
                }).sum::<usize>())
                .sum();
            tracing::info!(
                "[diag] turn={} messages={} tokens_est={} mem_est_bytes={} mem_est_mb={:.1}",
                self.total_turns,
                msg_count,
                token_est,
                mem_est,
                mem_est as f64 / 1_048_576.0,
            );
        }

        Ok(final_text)
    }

    /// Get total token usage.
    pub fn token_usage(&self) -> (u64, u64) {
        (self.total_input_tokens, self.total_output_tokens)
    }

    /// Get per-role token usage breakdown.
    pub fn role_token_usage(&self) -> &HashMap<String, (u64, u64)> {
        &self.role_token_usage
    }

    /// Build a conversation whose system prompt carries the project summary,
    /// skills, and the current memory knowledge.
    pub fn fresh_conversation(&self) -> Conversation {
        let mut conversation = Conversation::new(&self.project_dir);
        conversation.push_memory_knowledge(&self.memory.recall());
        conversation
    }

    /// Rebuild the active conversation from the project directory.
    pub fn reset_conversation(&mut self) {
        let conversation = self.fresh_conversation();
        self.conversation = conversation;
    }

    /// Reset the conversation — clears all messages AND rebuilds the
    /// system prompt from the project directory, so `/clear` followed by
    /// `/save` does not persist stale project context that was loaded at startup.
    pub fn reset(&mut self) {
        self.reset_conversation();
        self.total_input_tokens = 0;
        self.total_output_tokens = 0;
        self.role_token_usage.clear();

        // Re-apply sandbox note if sandbox is active
        if self.sandbox.working_dir() != &self.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            self.conversation.system_prompt.push_str(sandbox_note);
        }
    }
    // ── Loop detection / guardrail helpers ──────────────────────────────

}
/// Build a per-role Config map from the loaded models.toml.
///
/// For every entry in `[roles]` that references a valid model alias,
/// we pre-build a `Config` so callers can just do `role_configs["planner"]`
/// without repeating resolution logic.
fn build_role_configs(
    base: &Config,
    models_cfg: &model_manager::ModelsConfig,
) -> HashMap<String, Config> {
    let mut map = HashMap::new();
    for (role_name, role_cfg) in &models_cfg.roles {
        let config = base.for_role(role_name, models_cfg);
        // If system_prompt is set inline, we store it in the role entry; here
        // we only care about which model/provider/key to call.
        let _ = &role_cfg.system_prompt; // acknowledged, used later
        map.insert(role_name.clone(), config);
    }
    map
}

mod compaction;
mod knowledge;
mod project_summary;
mod subagent;
