//! Agent core: orchestrates LLM calls, tool execution, streaming,
//! context window management, and operation confirmation.

mod interrupt;
mod confirmation;
mod plan_mode;
mod tool_loop;

pub use interrupt::{clear_guidance, clear_interrupt, is_guidance_requested, is_interrupted, request_guidance, request_interrupt};
pub(crate) use interrupt::register_session_interrupt;
pub use confirmation::{ask_user_definition, build_confirm_action, needs_confirmation, with_ask_user, ConfirmationLevel};
pub(crate) use tool_loop::ToolLoopOptions;

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::{Context, Result};

use crate::config::{Config, Provider};
use crate::confirm::ConfirmAction;
use crate::context;
use crate::conversation::{ContentBlock, Conversation, ImageSource, Message, Role};
use crate::memory::{LocalFileMemory, MemoryEvent, MemoryProvider};
use crate::model_manager;
use crate::output::{AgentOutput, SilentOutput};
use crate::path_manager;
use crate::sandbox::Sandbox;
use crate::service::{ServiceEvent, SERVICE_EVENT_TX};
use crate::streaming;
use crate::tools::ToolExecutor;

/// The main Agent that orchestrates LLM calls and tool execution
pub struct Agent {
    pub config: Config,
    pub project_dir: PathBuf,
    pub(crate) tool_executor: ToolExecutor,
    pub conversation: Conversation,
    pub memory: Arc<dyn MemoryProvider>,
    total_input_tokens: u64,
    total_output_tokens: u64,
    /// Per-role token usage: maps role name → (input_tokens, output_tokens).
    /// Tracks cost breakdown across router, planner, executor, checker, agent, summary, etc.
    role_token_usage: HashMap<String, (u64, u64)>,
    pub(crate) session_id: Option<String>,
    pub(crate) output: Arc<dyn AgentOutput>,
    /// Holds a pending plan generated by `generate_plan()`, ready for `execute_plan()`.
    pub pending_plan: Option<String>,
    /// Plan-mode session state. When true the model sees only read-only tools plus
    /// exit_plan_mode, and must get an approved plan before implementing.
    pub plan_mode: bool,
    /// Delegation depth of this agent (0 = top-level). Bounds recursive sub-agent
    /// spawning so the model cannot spawn an unbounded chain.
    pub delegation_depth: usize,
    /// Live continuable sub-agent sessions, keyed by a sub-agent id. The model can
    /// follow up an existing sub-agent (subagent_followup) rather than only making
    /// one-shot spawns.
    pub subagents: Arc<tokio::sync::Mutex<HashMap<String, Arc<tokio::sync::Mutex<Agent>>>>>,
    /// Maximum sub-agent nesting depth before spawns are refused.
    pub max_subagent_depth: usize,
    /// Maximum number of concurrently live sub-agent sessions per agent.
    pub max_subagents: usize,
    /// Loaded models.toml config, kept for role resolution at runtime.
    pub models_cfg: model_manager::ModelsConfig,
    /// Per-role Config cache, built once on construction.
    /// Key is role name (e.g. "planner", "executor", "checker").
    pub(crate) role_configs: HashMap<String, Config>,
    /// Sandbox for snapshot-based rollback.
    pub sandbox: Sandbox,
    /// Path manager for unified path handling.
    pub path_manager: Arc<path_manager::PathManager>,
    /// When false (default), sessions are stored in the project's `.agent/session.json`.
    /// When true, sessions are stored in the global `~/.local/share/rust_agent/sessions/`.
    pub global_session: bool,
    /// Receiver for push notifications from external services.
    /// Drained at safe points (between tool iterations) and displayed via
    /// `AgentOutput::on_service_notification`.
    service_events: tokio::sync::broadcast::Receiver<ServiceEvent>,
    /// When set, overrides the adaptive router for every message.
    /// `None` means use the normal router logic.
    pub force_mode: Option<crate::router::ExecutionMode>,

    /// Plugin manager for plugin system integration
    pub plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>,
    /// Hook 事件总线（与 PluginManager 共享同一 Arc）
    pub(crate) hook_bus: Option<Arc<crate::plugin::hook_bus::HookBus>>,
    /// Number of completed message turns. Used to trigger periodic knowledge extraction.
    knowledge_extract_turns: u32,
    /// Total completed turns since agent was created. Passed to memory provider hooks.
    total_turns: u64,
    /// Per-session interrupt flag. Set by Ctrl-C handler or WebSocket "cancel"
    /// message. Checked between tool iterations so the agent can stop cleanly
    /// without leaving the conversation in an invalid state.
    pub(crate) interrupt_requested: Arc<AtomicBool>,
    // ── Loop detection / guardrail fields ────────────────────────────────
    /// Hash history of tool calls within the current turn
    /// (tool_name, args_hash) → how many times it's been repeated.
    pub(crate) turn_tool_call_hashes: HashMap<(String, u64), u32>,
    /// Number of consecutive turns with zero file mutations
    /// (write_file, edit_file, multi_edit_file).  Reset on mutation.
    pub(crate) turns_without_mutation: u32,
    /// Number of consecutive turns where the LLM produced identical tool calls.
    pub(crate) identical_tool_turns: u32,
    /// Snapshot of the previous turn's tool call hashes for cross-turn comparison.
    pub(crate) prev_turn_hashes: HashMap<(String, u64), u32>,
    /// Pluggable context engine for token estimation, truncation, and summarization.
    /// Defaults to `DefaultContextEngine`; can be swapped for custom strategies.
    pub context_engine: Box<dyn context::ContextEngine>,
}

impl Agent {
    /// Enable or disable sandbox mode dynamically
    pub fn set_sandbox_enabled(&mut self, enabled: bool) {
        if enabled && self.sandbox.working_dir() == &self.project_dir {
            // 如果沙盒当前是禁用的，尝试启用它
            let sandbox = crate::sandbox::Sandbox::new(&self.project_dir);
            self.sandbox = sandbox;
            // 更新 path manager
            let new_path_manager = Arc::new(path_manager::PathManager::with_sandbox(
                self.project_dir.clone(),
                Arc::new(self.sandbox.clone()),
            ));
            self.path_manager = new_path_manager.clone();
            // 更新工具执行器
            self.tool_executor.set_path_manager(new_path_manager);

            // 仅当 overlay 实际挂载成功（sandbox 不再是 disabled）时才注入系统提示词。
            // 如果 fuse-overlayfs 不可用，sandbox 静默回退为 disabled，此时绝对不能
            // 向 LLM 声称"处于沙盒隔离中"，否则 LLM 会误以为 rm -rf 等操作无害。
            if !self.sandbox.is_disabled {
                let sandbox_note = "\n\n## Sandbox Mode\n\
                - You are running in **sandbox mode** (overlay filesystem).\n\
                - All file operations are isolated in the sandbox directory.\n\
                - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
                - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
                - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
                if !self.conversation.system_prompt.contains("## Sandbox Mode") {
                    self.conversation.system_prompt.push_str(sandbox_note);
                }
            } else {
                // Overlay 不可用，记录警告（CLI 侧会通过 backend_label_sync 展示给用户）
                tracing::warn!("sandbox: fuse-overlayfs unavailable — sandbox disabled, NOT injecting sandbox system prompt");
            }
        } else if !enabled && self.sandbox.working_dir() != &self.project_dir {
            // 如果沙盒当前是启用的，禁用它
            self.sandbox = crate::sandbox::Sandbox::disabled(&self.project_dir);
            // 更新 path manager
            let new_path_manager = Arc::new(path_manager::PathManager::without_sandbox(
                self.project_dir.clone(),
            ));
            self.path_manager = new_path_manager.clone();
            // 更新工具执行器
            self.tool_executor.set_path_manager(new_path_manager);
            
            // 移除沙盒模式说明
            if let Some(start) = self.conversation.system_prompt.find("## Sandbox Mode") {
                if let Some(end) = self.conversation.system_prompt[start..].find("\n\n## ") {
                    self.conversation.system_prompt.replace_range(start..start+end, "");
                } else {
                    // 如果沙盒说明在末尾，直接截断
                    self.conversation.system_prompt.truncate(start);
                }
            }
        }
    }

    /// Update both `project_dir` and the tool executor's working directory.
    pub fn set_project_dir(&mut self, dir: PathBuf) {
        self.project_dir = dir.clone();
        self.tool_executor.set_project_dir(dir);
    }

    /// Restrict write/edit tools to paths inside `dir` for this agent.
    /// Pass `None` to remove the restriction.
    pub fn set_allowed_dir(&mut self, dir: Option<std::path::PathBuf>) {
        self.tool_executor.set_allowed_dir(dir.clone());
        // Also update path manager by creating a new one
        if let Some(path_manager) = Arc::get_mut(&mut self.path_manager) {
            path_manager.set_allowed_dir(dir);
        }
    }
    
    /// Load plugin tools from plugin manager
    pub async fn load_plugin_tools(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        self.tool_executor.load_plugin_tools().await
    }

    /// Connect to the supplied MCP server entries and register their tools.
    /// Used by server/worker mode where the client sends a `load_mcp` message.
    /// Returns `(loaded_tool_names, error_strings)`.
    pub async fn load_mcp_from_entries(
        &mut self,
        entries: &[crate::mcp_client::McpServerEntry],
    ) -> (Vec<String>, Vec<String>) {
        self.tool_executor.load_mcp_from_entries(entries).await
    }

    /// Unload all tools belonging to the MCP server identified by `prefix`.
    /// Returns the names of the removed tools.
    pub fn unload_mcp(&mut self, prefix: &str) -> Vec<String> {
        self.tool_executor.unload_mcp_by_prefix(prefix)
    }

    /// Return `(name, description)` pairs for all currently-loaded MCP tools.
    pub fn list_mcp_tools(&self) -> Vec<(String, String)> {
        self.tool_executor.list_mcp_tools()
    }

    // ── Per-session interrupt methods ───────────────────────────────────
    /// Request interruption of this specific agent session.
    pub fn request_interrupt(&self) {
        self.interrupt_requested.store(true, Ordering::Relaxed);
    }

    /// Clear the interrupt flag for this session.
    pub fn clear_interrupt(&self) {
        self.interrupt_requested.store(false, Ordering::Relaxed);
    }

    /// Check whether an interrupt has been requested for this session.
    pub fn is_interrupted(&self) -> bool {
        self.interrupt_requested.load(Ordering::Relaxed)
    }

    pub fn new(config: Config, project_dir: PathBuf, output: Arc<dyn AgentOutput>, sandbox: Sandbox, plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>) -> Self {
        let memory: Arc<dyn MemoryProvider> = crate::memory::create_memory_provider(
            &config.memory,
            &project_dir,
        ).unwrap_or_else(|e| {
            tracing::warn!("Failed to create memory provider: {}, falling back to local file memory", e);
            Arc::new(LocalFileMemory::load(&project_dir))
        });
        let mut conversation = Conversation::new(&project_dir);
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        
        // Create path manager
        let path_manager = Arc::new(path_manager::PathManager::with_sandbox(
            project_dir.clone(),
            Arc::new(sandbox.clone()),
        ));
        
        // Per-session interrupt flag — registered in the global registry so
        // Ctrl-C / WebSocket "cancel" can interrupt this session.
        let interrupt_requested = Arc::new(AtomicBool::new(false));
        register_session_interrupt(&interrupt_requested);
        
        let mut agent = Agent {
            config,
            tool_executor: ToolExecutor::new(effective_dir, output.clone(), plugin_manager.clone()),
            conversation,
            memory: memory.clone(),
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: None,
            output,
            project_dir,
            pending_plan: None,
            plan_mode: false,
            delegation_depth: 0,
            subagents: Arc::new(tokio::sync::Mutex::new(HashMap::new())),
            max_subagent_depth: 3,
            max_subagents: 8,
            models_cfg,
            role_configs,
            sandbox,
            path_manager,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,

            plugin_manager,
            hook_bus: None,
            knowledge_extract_turns: 0,
            total_turns: 0,
            interrupt_requested,
            turn_tool_call_hashes: HashMap::new(),
            turns_without_mutation: 0,
            identical_tool_turns: 0,
            prev_turn_hashes: HashMap::new(),
            context_engine: Box::new(context::DefaultContextEngine),
        };
        
        // Set path manager in tool executor
        agent.tool_executor.set_path_manager(agent.path_manager.clone());
        
        // Register memory tool so the LLM can manage its own memory
        agent.tool_executor.register_memory_tool(memory);
        
        // Take the initial frozen snapshot of knowledge for the system prompt.
        // This locks the knowledge in place for the session, protecting LLM prefix
        // cache (subsequent tool writes don't change the system prompt).
        agent.memory.take_knowledge_snapshot();
        
        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Create agent with a restored conversation
    pub fn with_conversation(config: Config, project_dir: PathBuf, conversation: Conversation, session_id: String, output: Arc<dyn AgentOutput>, sandbox: Sandbox, plugin_manager: Option<Arc<tokio::sync::Mutex<crate::plugin::PluginManager>>>) -> Self {
        let memory: Arc<dyn MemoryProvider> = Arc::new(LocalFileMemory::load(&project_dir));
        let conv_depth = conversation.delegation_depth;
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        // Create path manager
        let path_manager = Arc::new(path_manager::PathManager::with_sandbox(
            project_dir.clone(),
            Arc::new(sandbox.clone()),
        ));
        
        // Per-session interrupt flag
        let interrupt_requested = Arc::new(AtomicBool::new(false));
        register_session_interrupt(&interrupt_requested);
        
        let mut agent = Agent {
            config,
            tool_executor: ToolExecutor::new(effective_dir, output.clone(), plugin_manager.clone()),
            conversation,
            memory: memory.clone(),
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: Some(session_id),
            output,
            project_dir,
            pending_plan: None,
            plan_mode: false,
            delegation_depth: conv_depth,
            subagents: Arc::new(tokio::sync::Mutex::new(HashMap::new())),
            max_subagent_depth: 3,
            max_subagents: 8,
            models_cfg,
            role_configs,
            sandbox,
            path_manager,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,

            plugin_manager,
            hook_bus: None,
            knowledge_extract_turns: 0,
            total_turns: 0,
            interrupt_requested,
            turn_tool_call_hashes: HashMap::new(),
            turns_without_mutation: 0,
            identical_tool_turns: 0,
            prev_turn_hashes: HashMap::new(),
            context_engine: Box::new(context::DefaultContextEngine),
        };
        
        // Set path manager in tool executor
        agent.tool_executor.set_path_manager(agent.path_manager.clone());
        
        // Register memory tool so the LLM can manage its own memory
        agent.tool_executor.register_memory_tool(memory);
        
        // Take the initial frozen snapshot (for restored conversation).
        agent.memory.take_knowledge_snapshot();
        
        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Get or create a session ID for persistence
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Set session ID and notify memory providers of the switch.
    pub fn set_session_id(&mut self, id: String) {
        let old_id = self.session_id.take();
        let old_str = old_id.as_deref().unwrap_or("");
        self.session_id = Some(id.clone());
        self.memory.on_session_switch(&id, old_str, false);
    }

    /// 设置 Hook 事件总线共享引用。
    /// 由 cli.rs 在 load_all_plugins 完成后调用，同时也将 hook_bus 传递给内部的 ToolExecutor。
    pub fn set_hook_bus(&mut self, bus: Option<Arc<crate::plugin::hook_bus::HookBus>>) {
        self.tool_executor.set_hook_bus(bus.clone());
        self.hook_bus = bus;
    }

    /// 获取 Hook 事件总线共享引用。
    pub fn hook_bus(&self) -> Option<Arc<crate::plugin::hook_bus::HookBus>> {
        self.hook_bus.clone()
    }

    /// Switch the active model at runtime.
    pub fn switch_model(&mut self, resolved: &crate::model_manager::ResolvedModel) {
        self.config = self.config.with_resolved_model(resolved);
    }

    /// Drain all pending service push events and display them via
    /// `AgentOutput::on_service_notification`.
    ///
    /// Called at **safe points** — between tool iterations in the main loop
    /// and between REPL prompts in cli.rs — so notifications never interrupt
    /// LLM streaming mid-token.
    pub(crate) fn drain_service_events(&mut self) {
        use tokio::sync::broadcast::error::TryRecvError;
        loop {
            match self.service_events.try_recv() {
                Ok(ev) => {
                    self.output.on_service_notification(&ev.source, ev.level, &ev.message);
                }
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Lagged(n)) => {
                    self.output.on_service_notification(
                        "system",
                        crate::output::NotifyLevel::Warning,
                        &format!("Dropped {} service notifications (channel lagged)", n),
                    );
                }
                Err(TryRecvError::Closed) => break,
            }
        }
    }

    /// Maximum number of retries for transient LLM API errors.
    const LLM_MAX_RETRIES: u32 = 3;

    /// Check whether an error message indicates a transient/recoverable failure.
    pub(crate) fn is_transient_error(err_msg: &str) -> bool {
        let lower = err_msg.to_lowercase();
        lower.contains("dns error")
            || lower.contains("connection reset")
            || lower.contains("connection refused")
            || lower.contains("timed out")
            || lower.contains("timeout")
            || lower.contains("broken pipe")
            || lower.contains("try again")
            || lower.contains("temporarily unavailable")
            || lower.contains("eof before")
            || lower.contains("connection closed")
            || lower.contains("connection aborted")
            || lower.contains("network unreachable")
            || lower.contains("host unreachable")
            || lower.contains("error sending request")
            || lower.contains("failed to send")
            || lower.contains("failed to lookup address")
            || lower.contains("api error (429)")
            || lower.contains("api error (500)")
            || lower.contains("api error (502)")
            || lower.contains("api error (503)")
            || lower.contains("api error (504)")
            || lower.contains("overloaded")
    }

    /// Call the LLM using the config for a specific role.
    ///
    /// Falls back to `self.config` when the role is not configured.
    /// Emits an info-level UI note showing which model is active.
    pub(crate) async fn call_llm_as_role(
        &self,
        role: &str,
        conversation: &Conversation,
        tools: &[crate::tools::ToolDefinition],
    ) -> Result<crate::llm::LlmResponse> {
        let role_cfg = self.role_configs.get(role);
        let cfg = role_cfg.unwrap_or(&self.config);
        let role_label = match role {
            "planner"    => "🧠 Planner",
            "executor"   => "⚙️  Executor",
            "checker"    => "🔍 Checker",
            "router"     => "🔀 Router",
            "summarizer" => "📝 Summarizer",
            "agent"      => "🤖 Agent",
            other        => other,
        };
        // Show the role/model banner before a response.
        let model_name = cfg.model_alias.as_deref().unwrap_or(&cfg.model).to_string();
        self.output.on_role_header(role_label, &model_name);
        self.output.on_thinking();

        let mut last_err = None;
        for attempt in 0..=Self::LLM_MAX_RETRIES {
            let result = match cfg.provider {
                Provider::Anthropic => {
                    streaming::stream_anthropic_response(cfg, conversation, tools, &*self.output).await
                }
                Provider::OpenAI | Provider::Compatible => {
                    streaming::stream_openai_response(cfg, conversation, tools, &*self.output).await
                }
            };
            match result {
                Ok(response) => return Ok(response),
                Err(e) => {
                    // {:#} prints the ANYHOW cause chain, so a transport failure
                    // (DNS / proxy / TLS / connect timeout) is visible instead of
                    // just the generic "Failed to send streaming request" context.
                    let err_msg = format!("{:#}", e);
                    if Self::is_transient_error(&err_msg) && attempt < Self::LLM_MAX_RETRIES {
                        let delay = 2u64.pow(attempt + 1);
                        self.output.on_warning(&format!(
                            "API request failed (attempt {}/{}): {}. Retrying in {}s...",
                            attempt + 1, Self::LLM_MAX_RETRIES + 1, err_msg, delay
                        ));
                        tokio::time::sleep(std::time::Duration::from_secs(delay)).await;
                        last_err = Some(e);
                    } else {
                        return Err(e);
                    }
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow::anyhow!("LLM request failed after retries")))
    }

    /// Override the adaptive router for all subsequent messages.
    /// Pass `None` to restore normal router behaviour.
    pub fn set_force_mode(&mut self, mode: Option<crate::router::ExecutionMode>) {
        self.force_mode = mode;
    }

    /// Determine the execution mode for a given user message.
    ///
    /// If `force_mode` is set it takes priority over everything else.
    /// Otherwise the always-basic-loop default is used.
    pub async fn resolve_execution_mode(
        &self,
        _user_input: &str,
    ) -> crate::router::ExecutionMode {
        // The router is retired: the model drives plan-mode (plan_mode
        // flag) and delegation (call_node). Honor an explicit force_mode (e.g.
        // /mode) for command compatibility, otherwise always run the basic loop.
        if let Some(forced) = self.force_mode {
            return forced;
        }
        crate::router::ExecutionMode::BasicLoop
    }

    pub fn output_arc(&self) -> Arc<dyn AgentOutput> {
        self.output.clone()
    }

    /// Enter or leave plan mode. While on, the model sees only read-only tools
    /// plus exit_plan_mode; an approved plan is required before it can act.
    pub fn set_plan_mode(&mut self, on: bool) {
        self.plan_mode = on;
    }

    /// Whether plan mode is currently active.
    pub fn in_plan_mode(&self) -> bool {
        self.plan_mode
    }

    /// Run an in-process sub-agent and return a [crate::tools::ToolResult].
    ///
    /// If output_schema is given, the sub-agent is instructed to return a JSON
    /// value conforming to that schema, and the result carries that JSON
    /// (pretty-printed), or a structured error if the output does not parse.
    /// Without a schema, it returns the sub-agent's final free-text output.
    pub(crate) async fn run_subagent(
        &self,
        task: &str,
        output_schema: Option<&serde_json::Value>,
        fork: bool,
    ) -> crate::tools::ToolResult {
        let effective_task = match output_schema {
            Some(schema) => format!(
                "{}\n\n[STRUCTURED OUTPUT]\nReturn your final answer as a single JSON value conforming to this JSON Schema. Do NOT wrap it in markdown code fences and do NOT add any other prose. Return ONLY the JSON value as your final message.\n\n{}\n",
                task, schema
            ),
            None => task.to_string(),
        };
        match self.spawn_subagent_session(&effective_task, fork).await {
            Ok((id, text)) => {
                if output_schema.is_some() {
                    match Self::extract_json_value(&text) {
                        Some(json) => crate::tools::ToolResult::success(
                            serde_json::json!({ "subagentId": id, "result": json }).to_string(),
                        ),
                        None => crate::tools::ToolResult::error(format!(
                            "Sub-agent did not return a JSON value matching the requested schema.\n\nRaw output:\n{}",
                            text
                        )),
                    }
                } else {
                    crate::tools::ToolResult::success(
                        serde_json::json!({ "subagentId": id, "result": text }).to_string(),
                    )
                }
            }
            Err(e) => crate::tools::ToolResult::error(format!("Sub-agent failed: {:#}", e)),
        }
    }

    /// Spawn a continuable in-process sub-agent and run task, returning a
    /// (subagent_id, final_text) pair. The child is registered in this agent's
    /// live sub-agent registry so a later subagent_followup can continue it.
    /// Honors the delegation-depth bound (max_subagent_depth).
    pub(crate) async fn spawn_subagent_session(
        &self,
        task: &str,
        fork: bool,
    ) -> Result<(String, String)> {
        if self.delegation_depth >= self.max_subagent_depth {
            anyhow::bail!(
                "sub-agent depth limit reached ({}) — refusing to spawn deeper",
                self.max_subagent_depth
            );
        }
        {
            let reg = self.subagents.lock().await;
            if reg.len() >= self.max_subagents {
                anyhow::bail!(
                    "sub-agent quota reached ({}) — terminate one via subagent_terminate",
                    self.max_subagents
                );
            }
        }
        let mut child = Agent::new(
            self.config.clone(),
            self.project_dir.clone(),
            self.output.clone(),
            self.sandbox.clone(),
            self.plugin_manager.clone(),
        );
        child.delegation_depth = self.delegation_depth + 1;
        child.max_subagent_depth = self.max_subagent_depth;
        child.max_subagents = self.max_subagents;
        if fork {
            child.conversation = self.conversation.fork(self.conversation.log.len() as u64);
        }
        child.conversation.delegation_depth = child.delegation_depth;
        let id = format!("sa-{}", uuid::Uuid::new_v4());
        let child_arc = Arc::new(tokio::sync::Mutex::new(child));
        self.subagents.lock().await.insert(id.clone(), child_arc.clone());
        let text = {
            let mut guard = child_arc.lock().await;
            // Box the recursive call: process_message -> run_tool_loop -> spawn.
            Box::pin(guard.process_message(task)).await?
        };
        Ok((id, text))
    }

    /// Send a follow-up to a live sub-agent (by id) and return its next result.
    /// The sub-agent keeps its conversation, so this is multi-turn delegation.
    pub(crate) async fn subagent_followup(
        &self,
        id: &str,
        message: &str,
        output_schema: Option<&serde_json::Value>,
    ) -> crate::tools::ToolResult {
        let child = self.subagents.lock().await.get(id).cloned();
        match child {
            Some(child_arc) => {
                let result = {
                    let mut guard = child_arc.lock().await;
                    Box::pin(guard.process_message(message)).await
                };
                match result {
                    Ok(text) => {
                        if output_schema.is_some() {
                            match Self::extract_json_value(&text) {
                                Some(json) => crate::tools::ToolResult::success(
                                    serde_json::json!({ "subagentId": id, "result": json }).to_string(),
                                ),
                                None => crate::tools::ToolResult::error(format!(
                                    "Sub-agent did not return JSON matching the schema.\n\nRaw output:\n{}",
                                    text
                                )),
                            }
                        } else {
                            crate::tools::ToolResult::success(
                                serde_json::json!({ "subagentId": id, "result": text }).to_string(),
                            )
                        }
                    }
                    Err(e) => crate::tools::ToolResult::error(format!("Sub-agent follow-up failed: {:#}", e)),
                }
            }
            None => crate::tools::ToolResult::error(format!("unknown sub-agent id: {}", id)),
        }
    }
    /// Remove a live sub-agent from the registry, freeing its quota slot.
    pub(crate) async fn terminate_subagent(&self, id: &str) -> bool {
        self.subagents.lock().await.remove(id).is_some()
    }

    /// Best-effort extraction of a JSON value from sub-agent output. Try a direct
    /// parse of the trimmed text, then fall back to the first balanced {..} or [..]
    /// block (covers a model that wraps the JSON in prose).
    fn extract_json_value(text: &str) -> Option<serde_json::Value> {
        let t = text.trim();
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(t) {
            return Some(v);
        }
        for open in ['{', '['] {
            if let Some(start) = t.find(open) {
                let close = if open == '{' { '}' } else { ']' };
                if let Some(end_rel) = t[start..].rfind(close) {
                    let end = start + end_rel + 1;
                    if let Ok(v) = serde_json::from_str::<serde_json::Value>(&t[start..end]) {
                        return Some(v);
                    }
                }
            }
        }
        None
    }


    /// 发射 `router.decision` intercepting hook，允许插件覆盖路由模式。
    /// 脚本失败/超时均回退为原模式，不阻断主流程。
    async fn apply_router_hook(
        &self,
        mode: crate::router::ExecutionMode,
        user_input: &str,
    ) -> crate::router::ExecutionMode {
        use crate::router::ExecutionMode;
        use crate::plugin::hook_bus::{HookEvent, HookResult};

        let bus = match &self.hook_bus {
            Some(b) => b.clone(),
            None => return mode,
        };

        let mode_str = match mode {
            ExecutionMode::BasicLoop => "basic_loop",
        };
        let classification_source = if self.force_mode.is_some() { "forced" } else { "auto" };
        let task_preview: String = user_input.chars().take(200).collect();

        let event = HookEvent::new(
            "router.decision",
            self.session_id.as_deref().unwrap_or("none").to_string(),
            serde_json::json!({
                "proposed_mode":        mode_str,
                "classification_source": classification_source,
                "task_preview":          task_preview,
            }),
        );

        match bus.emit_intercepting(event).await {
            HookResult::PatchParams { params } => {
                let override_str = params
                    .get("override_mode")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                let new_mode = match override_str {
                    "basic_loop" => ExecutionMode::BasicLoop,
                    other => {
                        self.output.on_warning(&format!(
                            "[hook] router.decision: unknown override_mode '{}', keeping '{}'",
                            other, mode_str
                        ));
                        return mode;
                    }
                };
                if new_mode != mode {
                    let new_str = match new_mode {
                        ExecutionMode::BasicLoop => "basic_loop",
                    };
                    self.output.on_warning(&format!(
                        "🔀 Router overridden by hook: {} → {}",
                        mode_str, new_str
                    ));
                }
                new_mode
            }
            // Cancel / Approved 不阻断路由，降级为原决策
            HookResult::Cancel { reason } => {
                self.output.on_warning(&format!(
                    "[hook] router.decision cancelled ({}), keeping '{}'",
                    reason, mode_str
                ));
                mode
            }
            HookResult::Approved { .. } | HookResult::Continue => mode,
        }
    }

    /// Generate a brief explanation of what a tool is about to do and answer
    /// the user's question. Uses a lightweight LLM call (no tools).

    /// Query the hook system to see if a confirmation should be auto-approved,
    /// auto-denied, or left to the normal UI flow.
    ///
    /// Returns:
    ///   `Some(true)`  — hook approved; skip UI prompt
    ///   `Some(false)` — hook denied;   skip UI prompt
    ///   `None`        — no hook verdict; fall through to normal UI

    // ── Unified tool loop ─────────────────────────────────────────────────

    /// The unified tool loop that powers `process_message`.
    ///
    /// Each caller selects the subset of features via `opts` while the core
    /// LLM→tools→results→context cycle is shared.

    /// Process a user message and return the final text response.
    /// This handles the full agent loop: send message → receive response →
    /// if tool use → execute tools → send results → repeat until done.
    pub async fn process_message(&mut self, user_input: &str) -> Result<String> {
        // ── Router decision hook ─────────────────────────────────────────
        // Emit the (retired) router.decision hook so plugins can still observe
        // / override the mode, then fall through to the basic loop. Only
        // basic_loop is meaningful now; planning is driven by plan_mode.
        let mode = self.resolve_execution_mode(user_input).await;
        let _ = self.apply_router_hook(mode, user_input).await;

        // Prepend relevant memory context — used by all execution modes.
        let recall = self.memory.recall_relevant(user_input);
        let mut enriched_input = if recall.is_empty() {
            user_input.to_string()
        } else {
            format!("{}\n\n{}", recall, user_input)
        };


        // ── Sync global interrupt to per-session flag ─────────────────────
        // If a Ctrl-C happened before this turn started, propagate it to our
        // session flag and clear the global so we don't see it again next time.
        if is_interrupted() {
            self.request_interrupt();
            clear_interrupt();
        }

        // ── Reset loop detection counters for new turn ──────────────────
        self.turn_tool_call_hashes.clear();
        self.turns_without_mutation = 0;
        // Note: identical_tool_turns and prev_turn_hashes are NOT reset here
        // — they track patterns *across* turns, not within a single turn.

        // ── Turn start: notify memory providers ─────────────────────────
        self.total_turns += 1;
        self.conversation.append_turn_start(self.total_turns as u64);
        let max_tokens = self.context_engine.max_context_tokens(&self.config.model);
        let used_tokens = context::estimate_conversation_tokens(&self.conversation);
        let remaining_tokens = max_tokens.saturating_sub(used_tokens) as u64;
        self.memory.on_turn_start(
            self.total_turns as u32,
            user_input,
            remaining_tokens,
            &self.config.model,
        );

        if self.plan_mode {
            enriched_input = format!(
                "{}

[PLAN MODE GUIDANCE]
{}",
                plan_mode::plan_mode_guidance(),
                enriched_input
            );
        }

        // Add (already enriched) user message
        self.conversation.add_message(Message::user(&enriched_input));

        // Check context window before sending
        self.check_and_manage_context().await;

        let tool_defs = if self.plan_mode {
            confirmation::with_ask_user(
                plan_mode::plan_mode_toolset(self.tool_executor.readonly_definitions()),
            )
        } else {
            let mut defs = confirmation::with_ask_user(self.tool_executor.definitions());
            defs.push(plan_mode::subagent_definition());
            defs.push(plan_mode::subagent_fork_definition());
            defs.push(plan_mode::subagent_followup_definition());
            defs.push(plan_mode::subagent_terminate_definition());
            defs
        };

        // Per-turn tracking for record_interaction (zero extra LLM calls)
        let turn_start_tokens = self.total_input_tokens + self.total_output_tokens;
        let msg_count_before = self.conversation.messages.len();

        let opts = ToolLoopOptions {
            role: "agent".to_string(),
            enable_guardrails: true,
            enable_guidance: false,
            notify_file_created: true,
            handle_upload_image: true,
        };

        // Temporarily take ownership of the conversation so we can pass
        // a `&mut Conversation` to `run_tool_loop` without conflicting with
        // the `&mut self` borrow also required by that method.
        let mut conversation =
            std::mem::replace(&mut self.conversation, Conversation::new(&self.project_dir));
        let mut final_text = self
            .run_tool_loop(&mut conversation, &tool_defs, &opts)
            .await?;
        self.conversation = conversation;
        self.conversation.append_turn_end(self.total_turns as u64);
        if !self.conversation.log_is_consistent() {
            tracing::warn!(
                "[phase4] turn {} ended with a session log that diverged from the message surface;                  the log is authoritative and will be used on persistence",
                self.total_turns
            );
        }

        // If run_tool_loop returned empty (e.g. loop exhausted), fall back to
        // scanning the conversation for the last assistant text.
        if final_text.is_empty() {
            final_text = self
                .conversation
                .messages
                .iter()
                .rev()
                .find(|m| m.role == crate::conversation::Role::Assistant)
                .map(|m| m.text_content())
                .unwrap_or_default();
        }

        // Derive turn_tools_used and turn_had_errors from the messages added
        // during this turn (scanned from the conversation).
        // NOTE: msg_count_before may exceed current len if run_tool_loop
        // internally truncated the conversation (e.g. context compression).
        let start_idx = msg_count_before.min(self.conversation.messages.len());
        let new_msgs = &self.conversation.messages[start_idx..];
        let mut turn_tools_used: Vec<String> = Vec::new();
        let mut turn_had_errors = false;
        for msg in new_msgs {
            for block in &msg.content {
                if let ContentBlock::ToolUse { name, .. } = block {
                    turn_tools_used.push(name.clone());
                }
                if let ContentBlock::ToolResult { is_error, .. } = block {
                    if is_error.unwrap_or(false) {
                        turn_had_errors = true;
                    }
                }
            }
        }

        // Periodic knowledge extraction: every 5 turns, silently distill facts.
        self.knowledge_extract_turns += 1;
        if self.knowledge_extract_turns % 5 == 0 {
            self.extract_and_store_knowledge().await;
        }

        // Periodic diagnostics: every 10 turns, log conversation stats so we
        // can correlate hook-script timeouts with memory / context growth.
        if self.knowledge_extract_turns % 10 == 0 {
            let msg_count = self.conversation.messages.len();
            let token_est = context::estimate_conversation_tokens(&self.conversation);
            let mem_est: usize = self.conversation.messages.iter()
                .map(|m| m.content.iter().map(|b| match b {
                    ContentBlock::Text { text } => text.len(),
                    ContentBlock::ToolResult { content, .. } => content.len(),
                    ContentBlock::Thinking { thinking, .. } => thinking.len(),
                    _ => 256,
                }).sum::<usize>())
                .sum();
            tracing::info!(
                "[diag] turn={} messages={} tokens_est={} mem_est_bytes={} mem_est_mb={:.1}",
                self.total_turns,
                msg_count,
                token_est,
                mem_est,
                mem_est as f64 / 1_048_576.0,
            );
        }

        // Record complete interaction episode to intelligent memory.
        // intent_summary = first sentence of the assistant reply (zero extra tokens).
        let intent_summary = {
            let text = final_text.trim();
            text.split(['.', '\n', '\u{3002}']) // '。' for CJK
                .next()
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| text.chars().take(120).collect())
        };
        let turn_tokens = ((self.total_input_tokens + self.total_output_tokens)
            .saturating_sub(turn_start_tokens)) as u32;
        let (outcome_ok, outcome_detail) = if turn_had_errors {
            (false, "One or more tool calls encountered errors".to_string())
        } else {
            (true, intent_summary.clone())
        };
        self.memory.record_interaction(
            user_input,
            &intent_summary,
            &turn_tools_used,
            outcome_ok,
            &outcome_detail,
            &[], // lessons extracted separately by extract_and_store_knowledge
            None,
            turn_tokens,
        );

        Ok(final_text)
    }

    // ── Knowledge extraction ──────────────────────────────────────────────────

    /// Extract project facts from the recent conversation and store them in memory.
    ///
    /// Called automatically every 5 turns inside `process_message`. Uses a
    /// `SilentOutput` so it produces no visible output.
    async fn extract_and_store_knowledge(&self) {
        // Collect the last 10 messages as source material
        let msgs = &self.conversation.messages;
        let window: Vec<_> = msgs.iter().rev().take(10).collect();
        if window.is_empty() {
            return;
        }

        let mut context = String::new();
        for msg in window.into_iter().rev() {
            let role = match msg.role {
                Role::User      => "User",
                Role::Assistant => "Assistant",
                Role::System    => continue,
            };
            context.push_str(&format!("{}: {}\n", role, msg.text_content()));
        }

        let prompt = format!(
            "From the conversation below, extract 1-3 concise project facts worth \
            remembering across sessions. Only facts that are durable (architecture, \
            file locations, key decisions, recurring patterns). \
            Return ONLY a bullet list with no preamble: one fact per line starting with `-`.\n\n{}",
            context
        );

        let mut conv = Conversation::new(&self.project_dir);
        conv.system_prompt = "You are a knowledge extractor. Be concise.".to_string();
        conv.add_message(Message::user(&prompt));

        let silent = Arc::new(SilentOutput) as Arc<dyn AgentOutput>;
        let cfg = self.role_configs.get("summarizer").unwrap_or(&self.config);
        let result = match cfg.provider {
            Provider::Anthropic =>
                streaming::stream_anthropic_response(cfg, &conv, &[], &*silent).await,
            Provider::OpenAI | Provider::Compatible =>
                streaming::stream_openai_response(cfg, &conv, &[], &*silent).await,
        };

        if let Ok(response) = result {
            let text: String = response.content.iter()
                .filter_map(|b| if let ContentBlock::Text { text } = b { Some(text.as_str()) } else { None })
                .collect();
            let facts: Vec<String> = text.lines()
                .map(|l| l.trim().trim_start_matches('-').trim().to_string())
                .filter(|l| l.len() > 10)
                .take(3)
                .collect();
            if !facts.is_empty() {
                self.memory.record_event(crate::memory::MemoryEvent::KnowledgeExtracted { facts });
            }
        }
    }

    /// Manually consolidate memory: read recent session log and all existing knowledge,
    /// ask LLM to distill into improved knowledge entries and compress the log.
    ///
    /// Called by the `/consolidate` CLI command.
    pub async fn consolidate_memory(&self) -> anyhow::Result<usize> {
        let existing_knowledge = self.memory.knowledge();
        let session_log = self.memory.session_log();

        if session_log.is_empty() && existing_knowledge.is_empty() {
            return Ok(0);
        }

        let mut prompt = String::from(
            "You are distilling an AI agent's memory. \
            Given the session log and existing knowledge below, \
            produce an improved, deduplicated list of up to 10 project knowledge facts.\n\
            Rules: each fact must be a single sentence, durable across sessions, \
            no timestamps, no trivial observations.\n\
            Return ONLY the bullet list starting each line with `-`.\n\n"
        );

        if !existing_knowledge.is_empty() {
            prompt.push_str("## Existing Knowledge\n");
            for k in &existing_knowledge {
                prompt.push_str(&format!("- {}\n", k));
            }
        }
        if !session_log.is_empty() {
            prompt.push_str("\n## Session Log (most recent activity)\n");
            for entry in session_log.iter().rev().take(30) {
                prompt.push_str(&format!("- {}\n", entry));
            }
        }

        let mut conv = Conversation::new(&self.project_dir);
        conv.system_prompt = "You are a memory consolidation assistant.".to_string();
        conv.add_message(Message::user(&prompt));

        let silent = Arc::new(SilentOutput) as Arc<dyn AgentOutput>;
        let cfg = self.role_configs.get("summarizer").unwrap_or(&self.config);
        let response = match cfg.provider {
            Provider::Anthropic =>
                streaming::stream_anthropic_response(cfg, &conv, &[], &*silent).await?,
            Provider::OpenAI | Provider::Compatible =>
                streaming::stream_openai_response(cfg, &conv, &[], &*silent).await?,
        };

        let text: String = response.content.iter()
            .filter_map(|b| if let ContentBlock::Text { text } = b { Some(text.as_str()) } else { None })
            .collect();

        let facts: Vec<String> = text.lines()
            .map(|l| l.trim().trim_start_matches('-').trim().to_string())
            .filter(|l| l.len() > 10)
            .take(10)
            .collect();

        let count = facts.len();
        if count > 0 {
            self.memory.record_event(crate::memory::MemoryEvent::KnowledgeExtracted { facts });
        }
        Ok(count)
    }

    /// Execute a tool with diff preview for file modifications

    /// Track token usage for a specific role.
    fn track_tokens(&mut self, role: &str, usage: &crate::llm::Usage) {
        self.total_input_tokens += usage.input_tokens as u64;
        self.total_output_tokens += usage.output_tokens as u64;
        let entry = self.role_token_usage.entry(role.to_string()).or_insert((0, 0));
        entry.0 += usage.input_tokens as u64;
        entry.1 += usage.output_tokens as u64;
    }

    /// Check context window and truncate if needed.
    ///
    /// When truncation is required, attempts an LLM-driven summarization
    /// of the removed messages to preserve reasoning context. Falls back
    /// to a mechanical summary if the LLM call fails.
    async fn check_and_manage_context(&mut self) {
        let status = self.context_engine.check_context(&self.conversation, &self.config.model);

        if !status.needs_truncation {
            return;
        }

        self.output.on_context_warning(
            status.usage_percent,
            status.estimated_tokens,
            status.max_tokens,
        );

        // Emit hook: context.warning / context.critical
        if let Some(bus) = &self.hook_bus {
            let event_name = if status.usage_percent >= 90.0 {
                "context.critical"
            } else {
                "context.warning"
            };
            let session_id = self.session_id.as_deref().unwrap_or("none").to_string();
            let bus = bus.clone();
            let event = crate::plugin::hook_bus::HookEvent::new(
                event_name,
                session_id,
                serde_json::json!({
                    "used_tokens":  status.estimated_tokens,
                    "max_tokens":   status.max_tokens,
                    "ratio":        status.usage_percent / 100.0,
                    "model":        self.config.model,
                }),
            );
            bus.emit_blocking(event).await;
        }

        // Plan what to truncate (using the pluggable engine)
        let plan = match self.context_engine.plan_truncation(&self.conversation, &self.config.model) {
            Some(plan) => plan,
            None => {
                // Not enough messages to truncate meaningfully — fall back to
                // the legacy truncation which handles small-conversation edge cases.
                context::truncate_conversation(&mut self.conversation, &self.config.model, self.memory.as_ref());
                return;
            }
        };

        // Ask memory providers for pre-compression insights before messages are lost.
        let memory_insights = self.memory.on_pre_compress(
            &self.conversation.messages[plan.remove_start..plan.remove_end],
        );

        // Build condensed context from the messages about to be removed
        let mut truncation_context = context::build_truncation_context(
            &self.conversation.messages[plan.remove_start..plan.remove_end],
        );
        if !memory_insights.is_empty() {
            truncation_context.push_str("\n\n## Memory Provider Insights\n");
            truncation_context.push_str(&memory_insights);
        }

        // Try LLM-driven summarization
        let summary = match self.generate_truncation_summary(&truncation_context).await {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!("LLM summarization failed ({}), using engine's mechanical summary", e);
                self.context_engine.summarize_removed(
                    &self.conversation.messages[plan.remove_start..plan.remove_end],
                )
            }
        };

        self.context_engine.apply_truncation(&mut self.conversation, &plan, &summary, self.memory.as_ref());
    }

    /// Use the LLM to generate a narrative summary of truncated messages.
    ///
    /// This produces a much richer summary than the mechanical fallback,
    /// capturing intent, discoveries, and progress rather than just listing
    /// tool names.
    async fn generate_truncation_summary(&mut self, truncation_context: &str) -> Result<String> {
        let prompt = format!(
            r#"The following is a condensed log of a conversation between a user and an AI coding assistant that is about to be removed from context to save space. Generate a concise narrative summary (3-8 sentences) that captures:

1. What the user's goal/task was
2. What actions were taken (files read, edited, commands run)
3. What was discovered or accomplished
4. Any unresolved issues or next steps

Be factual and specific (include file names, function names, error messages). This summary will be injected back into the conversation so the assistant can maintain continuity.

--- CONVERSATION LOG ---
{}
--- END LOG ---

Summary:"#,
            truncation_context
        );

        let mut summary_conv = Conversation::new(&self.project_dir);
        summary_conv.system_prompt =
            "You are a precise technical summarizer. Output only the summary, no extra commentary. \
             Keep it under 200 words.".to_string();
        summary_conv.add_message(Message::user(&prompt));

        // Use the main model (or a "summarizer" role if configured)
        let response = self.call_llm_as_role("summarizer", &summary_conv, &[]).await?;

        if let Some(ref usage) = response.usage {
            self.track_tokens("summarizer", usage);
        }

        let text: String = response
            .content
            .iter()
            .filter_map(|b| {
                if let ContentBlock::Text { text } = b {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n");

        let text = text.trim().to_string();
        if text.is_empty() {
            anyhow::bail!("LLM returned empty summary");
        }

        Ok(text)
    }

    /// Get total token usage.
    pub fn token_usage(&self) -> (u64, u64) {
        (self.total_input_tokens, self.total_output_tokens)
    }

    /// Get per-role token usage breakdown.
    pub fn role_token_usage(&self) -> &HashMap<String, (u64, u64)> {
        &self.role_token_usage
    }

    /// Reset the conversation — clears all messages AND rebuilds the
    /// system prompt from the project directory.  This ensures that
    /// `/clear` followed by `/save` does not persist stale project
    /// context (summary, skills, memory) that was loaded at startup.
    pub fn reset(&mut self) {
        // Rebuild the entire conversation, which re-reads .agent/summary.md,
        // .agent/skills/, .agent/memory.md, and custom system_prompt.md files.
        self.conversation = Conversation::new(&self.project_dir);
        self.total_input_tokens = 0;
        self.total_output_tokens = 0;
        self.role_token_usage.clear();

        // Re-apply sandbox note if sandbox is active
        if self.sandbox.working_dir() != &self.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            self.conversation.system_prompt.push_str(sandbox_note);
        }

        // Re-take knowledge snapshot so the fresh system prompt is frozen
        self.memory.take_knowledge_snapshot();
    }

    /// Record a tool action to persistent memory.
    fn record_tool_to_memory(
        &self,
        tool_name: &str,
        tool_input: &serde_json::Value,
        result: &crate::tools::ToolResult,
    ) {
        let path = tool_input.get("path").and_then(|v| v.as_str()).unwrap_or("");

        match tool_name {
            "read_file" => {
                if !path.is_empty() {
                    self.memory.record_event(MemoryEvent::FileRead { path: path.to_string() });
                }
            }
            "write_file" => {
                if !path.is_empty() && !result.is_error {
                    let lines = tool_input
                        .get("content")
                        .and_then(|v| v.as_str())
                        .map(|c| c.lines().count())
                        .unwrap_or(0);
                    self.memory.record_event(MemoryEvent::FileWritten {
                        path: path.to_string(),
                        lines,
                    });
                }
            }
            "edit_file" => {
                if !path.is_empty() && !result.is_error {
                    self.memory.record_event(MemoryEvent::FileEdited { path: path.to_string() });
                }
            }
            "run_command" => {
                if !result.is_error {
                    let cmd = tool_input
                        .get("command")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    let short_cmd = crate::ui::truncate_str(cmd, 60).to_string();
                    self.memory.record_event(MemoryEvent::CommandRun { command: short_cmd });
                }
            }
            "grep_search" => {
                let pattern = tool_input
                    .get("pattern")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                if !pattern.is_empty() {
                    self.memory.record_event(MemoryEvent::GrepSearch {
                        pattern: pattern.to_string(),
                        path: if path.is_empty() { None } else { Some(path.to_string()) },
                    });
                }
            }
            "file_search" => {
                let pattern = tool_input
                    .get("pattern")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                if !pattern.is_empty() {
                    self.memory.record_event(MemoryEvent::FileFind { pattern: pattern.to_string() });
                }
            }
            "list_directory" => {
                let dir = if path.is_empty() { "." } else { path };
                self.memory.record_event(MemoryEvent::DirectoryListed { path: dir.to_string() });
            }
            "multi_edit_file" => {
                if !path.is_empty() && !result.is_error {
                    let edits = tool_input
                        .get("edits")
                        .and_then(|v| v.as_array())
                        .map(|a| a.len())
                        .unwrap_or(0);
                    self.memory.record_event(MemoryEvent::FileMultiEdited {
                        path: path.to_string(),
                        edits,
                    });
                }
            }
            "batch_read_files" => {
                if let Some(paths) = tool_input.get("paths").and_then(|v| v.as_array()) {
                    let collected: Vec<String> = paths
                        .iter()
                        .filter_map(|p| p.as_str().map(|s| s.to_string()))
                        .collect();
                    if !collected.is_empty() {
                        self.memory.record_event(MemoryEvent::BatchFilesRead { paths: collected });
                    }
                }
            }
            "read_pdf" => {
                if !path.is_empty() {
                    self.memory.record_event(MemoryEvent::PdfRead { path: path.to_string() });
                }
            }
            "think" => {
                // No memory update for think — it's internal reasoning
            }
            _ => {}
        }
        // Auto-save is handled inside LocalFileMemory::record_event — no explicit flush needed.
    }

    /// Save memory to disk (public, for use from CLI)
    #[allow(dead_code)]
    pub fn save_memory(&self) {
        if let Err(e) = self.memory.flush() {
            tracing::warn!("Failed to save memory: {}", e);
        }
    }

    /// Generate a plan for the given task without executing it.
    ///
    /// During the planning phase the LLM only has access to **read-only** tools
    /// (read_file, list_directory, grep_search, file_search) so it can explore
    /// the codebase but cannot modify anything.  The resulting plan text is
    /// stored in `self.pending_plan` and returned.
    pub async fn generate_project_summary(&mut self) -> Result<String> {
        let cwd = self.project_dir.clone();

        // Step 1: Scan directory structure (depth 2)
        let dir_result = self
            .tool_executor
            .execute(
                "list_directory",
                &serde_json::json!({ "path": ".", "recursive": true }),
            )
            .await;
        let dir_tree = if dir_result.is_error {
            "(failed to list directory)".to_string()
        } else {
            dir_result.output
        };

        // Step 2: Try to read key project files for extra context
        let key_files = [
            "README.md",
            "Cargo.toml",
            "package.json",
            "Makefile",
            "CMakeLists.txt",
            "pyproject.toml",
            "go.mod",
            "AGENT.md",
        ];
        let mut file_contents = Vec::new();
        for filename in &key_files {
            let path = cwd.join(filename);
            if path.exists() {
                let read_result = self
                    .tool_executor
                    .execute(
                        "read_file",
                        &serde_json::json!({
                            "path": filename,
                            "max_lines": 200
                        }),
                    )
                    .await;
                if !read_result.is_error {
                    file_contents.push(format!("--- {} ---\n{}", filename, read_result.output));
                }
            }
        }

        let files_context = if file_contents.is_empty() {
            String::new()
        } else {
            format!("\n\nKey file contents:\n{}", file_contents.join("\n\n"))
        };

        // Step 3: Build a one-shot prompt to generate the summary
        let prompt = format!(
            r#"Please analyze this project and generate a concise project summary (in the same language as any README or docs found). The summary should include:

1. **Project name and purpose** (1-2 sentences)
2. **Tech stack** (language, frameworks, key dependencies)
3. **Directory structure overview** (major modules/components)
4. **Build & run commands** (if discoverable)
5. **Key conventions** (coding style, patterns observed)

Keep it compact (under 30 lines). This summary will be stored and reused across sessions so the AI agent can quickly understand the project without re-reading everything.

Project directory: {}

Directory tree:
{}
{}"#,
            cwd.display(),
            dir_tree,
            files_context
        );

        // Step 4: Send to LLM using a temporary conversation (don't pollute main one)
        let mut summary_conversation = Conversation::new(&self.project_dir);
        summary_conversation.system_prompt =
            "You are a helpful assistant that generates concise project summaries. \
             Output only the summary content, no extra commentary."
                .to_string();
        summary_conversation.add_message(Message::user(&prompt));

        let response = self.call_llm_as_role("agent", &summary_conversation, &[]).await?;

        // Track token usage
        if let Some(ref usage) = response.usage {
            self.track_tokens("summary", usage);
        }

        // Extract text
        let summary_text: String = response
            .content
            .iter()
            .filter_map(|block| {
                if let ContentBlock::Text { text } = block {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n");

        let summary_text = summary_text.trim().to_string();
        if summary_text.is_empty() {
            anyhow::bail!("LLM returned an empty project summary");
        }

        // Step 5: Save to .agent/summary.md
        crate::summary::save(&cwd, &summary_text)?;

        // Step 6: Inject into current session's system prompt
        self.conversation
            .system_prompt
            .push_str(&crate::summary::to_system_prompt_section(&summary_text));

        Ok(summary_text)
    }

    // ── Loop detection / guardrail helpers ──────────────────────────────

}
/// Build a per-role Config map from the loaded models.toml.
///
/// For every entry in `[roles]` that references a valid model alias,
/// we pre-build a `Config` so callers can just do `role_configs["planner"]`
/// without repeating resolution logic.
fn build_role_configs(
    base: &Config,
    models_cfg: &model_manager::ModelsConfig,
) -> HashMap<String, Config> {
    let mut map = HashMap::new();
    for (role_name, role_cfg) in &models_cfg.roles {
        let config = base.for_role(role_name, models_cfg);
        // If system_prompt is set inline, we store it in the role entry; here
        // we only care about which model/provider/key to call.
        let _ = &role_cfg.system_prompt; // acknowledged, used later
        map.insert(role_name.clone(), config);
    }
    map
}