//! Agent core: orchestrates LLM calls, tool execution, streaming,
//! context window management, and operation confirmation.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::Result;
/// Set by the Ctrl-C handler; checked between tool calls so the agent
/// can stop cleanly without leaving the conversation in an invalid state.
static INTERRUPT_REQUESTED: AtomicBool = AtomicBool::new(false);

pub fn request_interrupt() {
    INTERRUPT_REQUESTED.store(true, Ordering::Relaxed);
}

pub fn clear_interrupt() {
    INTERRUPT_REQUESTED.store(false, Ordering::Relaxed);
}

pub fn is_interrupted() -> bool {
    INTERRUPT_REQUESTED.load(Ordering::Relaxed)
}

/// Set by the Ctrl-\ (SIGQUIT) handler; checked between LLM iterations in the
/// pipeline executor so the user can inject real-time guidance at any safe point.
static GUIDANCE_REQUESTED: AtomicBool = AtomicBool::new(false);

pub fn request_guidance() {
    GUIDANCE_REQUESTED.store(true, Ordering::Relaxed);
}

pub fn clear_guidance() {
    GUIDANCE_REQUESTED.store(false, Ordering::Relaxed);
}

pub fn is_guidance_requested() -> bool {
    GUIDANCE_REQUESTED.load(Ordering::Relaxed)
}

use crate::config::{Config, Provider};
use crate::confirm::ConfirmAction;
use crate::context;
use crate::conversation::{ContentBlock, Conversation, Message};
use crate::llm::{self, LlmClient};
use crate::memory::Memory;
use crate::model_manager;
use crate::output::AgentOutput;
use crate::sandbox::Sandbox;
use crate::service::{ServiceEvent, SERVICE_EVENT_TX};
use crate::streaming;
use crate::tools::ToolExecutor;

/// The main Agent that orchestrates LLM calls and tool execution
pub struct Agent {
    pub config: Config,
    pub project_dir: PathBuf,
    client: Box<dyn LlmClient>,
    tool_executor: ToolExecutor,
    pub conversation: Conversation,
    pub memory: Memory,
    total_input_tokens: u64,
    total_output_tokens: u64,
    /// Per-role token usage: maps role name → (input_tokens, output_tokens).
    /// Tracks cost breakdown across router, planner, executor, checker, agent, summary, etc.
    role_token_usage: HashMap<String, (u64, u64)>,
    session_id: Option<String>,
    output: Arc<dyn AgentOutput>,
    /// Holds a pending plan generated by `generate_plan()`, ready for `execute_plan()`.
    pub pending_plan: Option<String>,
    /// Loaded models.toml config, kept for role resolution at runtime.
    pub models_cfg: model_manager::ModelsConfig,
    /// Per-role Config cache, built once on construction.
    /// Key is role name (e.g. "planner", "executor", "checker").
    role_configs: HashMap<String, Config>,
    /// Sandbox for snapshot-based rollback.
    pub sandbox: Sandbox,
    /// When false (default), sessions are stored in the project's `.agent/session.json`.
    /// When true, sessions are stored in the global `~/.local/share/rust_agent/sessions/`.
    pub global_session: bool,
    /// Receiver for push notifications from external services.
    /// Drained at safe points (between tool iterations) and displayed via
    /// `AgentOutput::on_service_notification`.
    service_events: tokio::sync::broadcast::Receiver<ServiceEvent>,
    /// When set, overrides the adaptive router for every message.
    /// `None` means use the normal router logic.
    pub force_mode: Option<crate::router::ExecutionMode>,
}

impl Agent {
    /// Enable or disable sandbox mode dynamically
    pub fn set_sandbox_enabled(&mut self, enabled: bool) {
        if enabled && self.sandbox.working_dir() == &self.project_dir {
            // 如果沙盒当前是禁用的，尝试启用它
            let sandbox = crate::sandbox::Sandbox::new(&self.project_dir);
            self.sandbox = sandbox;
            // 更新工具执行器的工作目录
            self.set_allowed_dir(Some(self.sandbox.working_dir().to_path_buf()));

            // 仅当 overlay 实际挂载成功（sandbox 不再是 disabled）时才注入系统提示词。
            // 如果 fuse-overlayfs 不可用，sandbox 静默回退为 disabled，此时绝对不能
            // 向 LLM 声称"处于沙盒隔离中"，否则 LLM 会误以为 rm -rf 等操作无害。
            if !self.sandbox.is_disabled {
                let sandbox_note = "\n\n## Sandbox Mode\n\
                - You are running in **sandbox mode** (overlay filesystem).\n\
                - All file operations are isolated in the sandbox directory.\n\
                - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
                - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
                - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
                if !self.conversation.system_prompt.contains("## Sandbox Mode") {
                    self.conversation.system_prompt.push_str(sandbox_note);
                }
            } else {
                // Overlay 不可用，记录警告（CLI 侧会通过 backend_label_sync 展示给用户）
                tracing::warn!("sandbox: fuse-overlayfs unavailable — sandbox disabled, NOT injecting sandbox system prompt");
            }
        } else if !enabled && self.sandbox.working_dir() != &self.project_dir {
            // 如果沙盒当前是启用的，禁用它
            self.sandbox = crate::sandbox::Sandbox::disabled(&self.project_dir);
            // 恢复工具执行器的工作目录
            self.set_allowed_dir(Some(self.project_dir.clone()));
            
            // 移除沙盒模式说明
            if let Some(start) = self.conversation.system_prompt.find("## Sandbox Mode") {
                if let Some(end) = self.conversation.system_prompt[start..].find("\n\n## ") {
                    self.conversation.system_prompt.replace_range(start..start+end, "");
                } else {
                    // 如果沙盒说明在末尾，直接截断
                    self.conversation.system_prompt.truncate(start);
                }
            }
        }
    }

    /// Update both `project_dir` and the tool executor's working directory.
    pub fn set_project_dir(&mut self, dir: PathBuf) {
        self.project_dir = dir.clone();
        self.tool_executor.set_project_dir(dir);
    }

    /// Restrict write/edit tools to paths inside `dir` for this agent.
    /// Pass `None` to remove the restriction.
    pub fn set_allowed_dir(&mut self, dir: Option<std::path::PathBuf>) {
        self.tool_executor.set_allowed_dir(dir);
    }

    /// Spawn all MCP servers configured in `.agent/mcp.toml` and register
    /// their tools.  Call once after construction (in CLI / stdio mode).
    pub async fn load_mcp_tools(&mut self) {
        self.tool_executor.load_mcp_tools().await;
    }

    /// Connect to the supplied MCP server entries and register their tools.
    /// Used by server/worker mode where the client sends a `load_mcp` message.
    /// Returns `(loaded_tool_names, error_strings)`.
    pub async fn load_mcp_from_entries(
        &mut self,
        entries: &[crate::mcp_client::McpServerEntry],
    ) -> (Vec<String>, Vec<String>) {
        self.tool_executor.load_mcp_from_entries(entries).await
    }

    /// Unload all tools belonging to the MCP server identified by `prefix`.
    /// Returns the names of the removed tools.
    pub fn unload_mcp(&mut self, prefix: &str) -> Vec<String> {
        self.tool_executor.unload_mcp_by_prefix(prefix)
    }

    /// Return `(name, description)` pairs for all currently-loaded MCP tools.
    pub fn list_mcp_tools(&self) -> Vec<(String, String)> {
        self.tool_executor.list_mcp_tools()
    }

    pub fn new(config: Config, project_dir: PathBuf, output: Arc<dyn AgentOutput>, sandbox: Sandbox) -> Self {
        let client = llm::create_client(&config);
        let memory = Memory::load(&project_dir);
        let mut conversation = Conversation::new(&project_dir);
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        let mut agent = Agent {
            config,
            client,
            tool_executor: ToolExecutor::new(effective_dir, output.clone()),
            conversation,
            memory,
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: None,
            output,
            project_dir,
            pending_plan: None,
            models_cfg,
            role_configs,
            sandbox,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,
        };
        
        // 在沙盒模式下，限制文件操作只能在沙盒工作目录内
        agent.tool_executor.set_allowed_dir(Some(agent.sandbox.working_dir().to_path_buf()));
        
        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Create agent with a restored conversation
    pub fn with_conversation(config: Config, project_dir: PathBuf, conversation: Conversation, session_id: String, output: Arc<dyn AgentOutput>, sandbox: Sandbox) -> Self {
        let client = llm::create_client(&config);
        let memory = Memory::load(&project_dir);
        let models_cfg = model_manager::load();
        let role_configs = build_role_configs(&config, &models_cfg);
        let effective_dir = sandbox.working_dir().to_path_buf();
        let mut agent = Agent {
            config,
            client,
            tool_executor: ToolExecutor::new(effective_dir, output.clone()),
            conversation,
            memory,
            total_input_tokens: 0,
            total_output_tokens: 0,
            role_token_usage: HashMap::new(),
            session_id: Some(session_id),
            output,
            project_dir,
            pending_plan: None,
            models_cfg,
            role_configs,
            sandbox,
            global_session: false,
            service_events: SERVICE_EVENT_TX.subscribe(),
            force_mode: None,
        };
        
        // 在沙盒模式下，限制文件操作只能在沙盒工作目录内
        agent.tool_executor.set_allowed_dir(Some(agent.sandbox.working_dir().to_path_buf()));
        
        // 在沙盒模式下，添加路径使用说明到系统提示词
        if agent.sandbox.working_dir() != &agent.project_dir {
            let sandbox_note = "\n\n## Sandbox Mode\n\
            - You are running in **sandbox mode** (overlay filesystem).\n\
            - All file operations are isolated in the sandbox directory.\n\
            - **IMPORTANT**: Always use **relative paths** (e.g., `src/main.rs`) not absolute paths.\n\
            - Absolute paths to files outside the sandbox will be rejected with \"Access denied\".\n\
            - Use `/changes` to see modified files, `/rollback` to undo, `/commit` to apply changes.";
            
            agent.conversation.system_prompt.push_str(sandbox_note);
        }
        
        agent
    }

    /// Get or create a session ID for persistence
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Set session ID
    pub fn set_session_id(&mut self, id: String) {
        self.session_id = Some(id);
    }

    /// Switch the active model at runtime.
    /// Rebuilds the underlying LLM client with the new config.
    pub fn switch_model(&mut self, resolved: &crate::model_manager::ResolvedModel) {
        self.config = self.config.with_resolved_model(resolved);
        self.client = llm::create_client(&self.config);
    }

    /// Drain all pending service push events and display them via
    /// `AgentOutput::on_service_notification`.
    ///
    /// Called at **safe points** — between tool iterations in the main loop
    /// and between REPL prompts in cli.rs — so notifications never interrupt
    /// LLM streaming mid-token.
    pub fn drain_service_events(&mut self) {
        use tokio::sync::broadcast::error::TryRecvError;
        loop {
            match self.service_events.try_recv() {
                Ok(ev) => {
                    self.output.on_service_notification(&ev.source, ev.level, &ev.message);
                }
                Err(TryRecvError::Empty) => break,
                Err(TryRecvError::Lagged(n)) => {
                    self.output.on_service_notification(
                        "system",
                        crate::output::NotifyLevel::Warning,
                        &format!("Dropped {} service notifications (channel lagged)", n),
                    );
                }
                Err(TryRecvError::Closed) => break,
            }
        }
    }

    /// Maximum number of retries for transient LLM API errors.
    const LLM_MAX_RETRIES: u32 = 3;

    /// Check whether an error message indicates a transient/recoverable failure.
    fn is_transient_error(err_msg: &str) -> bool {
        let lower = err_msg.to_lowercase();
        lower.contains("dns error")
            || lower.contains("connection reset")
            || lower.contains("connection refused")
            || lower.contains("timed out")
            || lower.contains("timeout")
            || lower.contains("broken pipe")
            || lower.contains("try again")
            || lower.contains("temporarily unavailable")
            || lower.contains("eof before")
            || lower.contains("connection closed")
            || lower.contains("connection aborted")
            || lower.contains("network unreachable")
            || lower.contains("host unreachable")
            || lower.contains("error sending request")
            || lower.contains("failed to send")
            || lower.contains("failed to lookup address")
            || lower.contains("api error (429)")
            || lower.contains("api error (500)")
            || lower.contains("api error (502)")
            || lower.contains("api error (503)")
            || lower.contains("api error (504)")
            || lower.contains("overloaded")
    }

    /// Call the LLM with automatic retry for transient network errors
    /// (DNS failures, connection resets, timeouts, 5xx server errors, etc.).
    /// Uses exponential backoff: 2s, 4s, 8s between retries.
    async fn call_llm_with_retry(
        &self,
        conversation: &Conversation,
        tools: &[crate::tools::ToolDefinition],
    ) -> Result<crate::llm::LlmResponse> {
        // Show which model is handling this turn
        let model_name = self.config.model_alias.as_deref().unwrap_or(&self.config.model).to_string();
        self.output.on_role_header("🤖 Agent", &model_name);
        self.output.on_thinking();

        let mut last_err = None;
        for attempt in 0..=Self::LLM_MAX_RETRIES {
            let result = match self.config.provider {
                Provider::Anthropic => {
                    streaming::stream_anthropic_response(
                        &self.config,
                        conversation,
                        tools,
                        &*self.output,
                    )
                    .await
                }
                Provider::OpenAI | Provider::Compatible => {
                    streaming::stream_openai_response(
                        &self.config,
                        conversation,
                        tools,
                        &*self.output,
                    )
                    .await
                }
            };

            match result {
                Ok(response) => return Ok(response),
                Err(e) => {
                    let err_msg = format!("{}", e);
                    let is_transient = Self::is_transient_error(&err_msg);
                    if is_transient && attempt < Self::LLM_MAX_RETRIES {
                        let delay = 2u64.pow(attempt + 1);
                        self.output.on_warning(&format!(
                            "API request failed (attempt {}/{}): {}. Retrying in {}s...",
                            attempt + 1,
                            Self::LLM_MAX_RETRIES + 1,
                            err_msg,
                            delay
                        ));
                        tokio::time::sleep(std::time::Duration::from_secs(delay)).await;
                        last_err = Some(e);
                    } else {
                        return Err(e);
                    }
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow::anyhow!("LLM request failed after retries")))
    }

    /// Call the LLM using the config for a specific role.
    ///
    /// Falls back to `self.config` when the role is not configured.
    /// Emits an info-level UI note showing which model is active.
    async fn call_llm_as_role(
        &self,
        role: &str,
        conversation: &Conversation,
        tools: &[crate::tools::ToolDefinition],
    ) -> Result<crate::llm::LlmResponse> {
        let role_cfg = self.role_configs.get(role);
        let cfg = role_cfg.unwrap_or(&self.config);
        let role_label = match role {
            "planner"    => "🧠 Planner",
            "executor"   => "⚙️  Executor",
            "checker"    => "🔍 Checker",
            "router"     => "🔀 Router",
            "summarizer" => "📝 Summarizer",
            other        => other,
        };
        // Show role banner (visible even when pipeline uses a different model)
        let model_name = cfg.model_alias.as_deref().unwrap_or(&cfg.model).to_string();
        self.output.on_role_header(role_label, &model_name);
        self.output.on_thinking();

        let mut last_err = None;
        for attempt in 0..=Self::LLM_MAX_RETRIES {
            let result = match cfg.provider {
                Provider::Anthropic => {
                    streaming::stream_anthropic_response(cfg, conversation, tools, &*self.output).await
                }
                Provider::OpenAI | Provider::Compatible => {
                    streaming::stream_openai_response(cfg, conversation, tools, &*self.output).await
                }
            };
            match result {
                Ok(response) => return Ok(response),
                Err(e) => {
                    let err_msg = format!("{}", e);
                    if Self::is_transient_error(&err_msg) && attempt < Self::LLM_MAX_RETRIES {
                        let delay = 2u64.pow(attempt + 1);
                        self.output.on_warning(&format!(
                            "API request failed (attempt {}/{}): {}. Retrying in {}s...",
                            attempt + 1, Self::LLM_MAX_RETRIES + 1, err_msg, delay
                        ));
                        tokio::time::sleep(std::time::Duration::from_secs(delay)).await;
                        last_err = Some(e);
                    } else {
                        return Err(e);
                    }
                }
            }
        }
        Err(last_err.unwrap_or_else(|| anyhow::anyhow!("LLM request failed after retries")))
    }

    /// Return the pipeline config from models.toml (if any).
    pub fn pipeline_config(&self) -> Option<&model_manager::PipelineConfig> {
        self.models_cfg.pipeline.as_ref()
    }

    /// Return true when the multi-role pipeline is enabled in models.toml.
    /// NOTE: Prefer `resolve_execution_mode()` for adaptive routing.
    pub fn pipeline_enabled(&self) -> bool {
        self.models_cfg
            .pipeline
            .as_ref()
            .map(|p| p.enabled)
            .unwrap_or(false)
    }

    /// Override the adaptive router for all subsequent messages.
    /// Pass `None` to restore normal router behaviour.
    pub fn set_force_mode(&mut self, mode: Option<crate::router::ExecutionMode>) {
        self.force_mode = mode;
    }

    /// Determine the execution mode for a given user message.
    ///
    /// If `force_mode` is set it takes priority over everything else.
    /// Otherwise uses the router configuration from models.toml:
    /// - `router = "auto"`:            heuristic + optional LLM classification
    /// - `router = "always_pipeline"`:  always full pipeline
    /// - `router = "always_simple"`:    always basic loop
    /// - absent + `enabled = true`:     always full pipeline (backward compat)
    /// - absent + `enabled = false`:    always basic loop
    pub async fn resolve_execution_mode(
        &self,
        user_input: &str,
    ) -> crate::router::ExecutionMode {
        use crate::router::{ExecutionMode, RouterMode};

        // Manual override always wins.
        if let Some(forced) = self.force_mode {
            return forced;
        }

        let router_mode = self
            .models_cfg
            .pipeline
            .as_ref()
            .map(|p| p.router_mode())
            .unwrap_or(RouterMode::AlwaysSimple);

        match router_mode {
            RouterMode::AlwaysPipeline => ExecutionMode::FullPipeline,
            RouterMode::AlwaysSimple => ExecutionMode::BasicLoop,
            RouterMode::Auto => self.classify_task(user_input).await,
        }
    }

    /// Classify a task using heuristics, falling back to an LLM call
    /// when the heuristics are inconclusive.
    async fn classify_task(
        &self,
        user_input: &str,
    ) -> crate::router::ExecutionMode {
        use crate::router::*;

        // Tier 1: rule-based heuristics (free, instant)
        if let Some(complexity) = classify_heuristic(user_input) {
            self.output.on_warning(&format!(
                "🔀 Router (heuristic): {} → {}",
                complexity,
                ExecutionMode::from(complexity)
            ));
            return ExecutionMode::from(complexity);
        }

        // Tier 2: lightweight LLM classification
        let prompt = build_classification_prompt(user_input);
        let mut classify_conv = Conversation::new(&self.project_dir);
        classify_conv.system_prompt =
            "You are a task classifier. Reply with exactly one word.".to_string();
        classify_conv.add_message(Message::user(&prompt));

        // Use a fast call with no tools — minimal cost
        match self.call_llm_as_role("router", &classify_conv, &[]).await {
            Ok(response) => {
                let text: String = response
                    .content
                    .iter()
                    .filter_map(|b| {
                        if let ContentBlock::Text { text } = b {
                            Some(text.as_str())
                        } else {
                            None
                        }
                    })
                    .collect();
                let complexity = parse_classification(&text);
                let mode = ExecutionMode::from(complexity);
                self.output.on_warning(&format!(
                    "🔀 Router (LLM): {} → {}",
                    complexity, mode
                ));
                mode
            }
            Err(e) => {
                // If classification fails, default to basic loop (safe, cheap)
                self.output.on_warning(&format!(
                    "🔀 Router: classification failed ({}), defaulting to Basic Loop",
                    e
                ));
                ExecutionMode::BasicLoop
            }
        }
    }

    /// Get a clone of the output Arc (used by pipeline.rs).
    pub fn output_arc(&self) -> Arc<dyn AgentOutput> {
        self.output.clone()
    }

    /// Build the tool definition for the virtual `ask_user` tool.
    ///
    /// This tool is NOT registered in `ToolExecutor`; it's intercepted in the
    /// agent loop and handled via `AgentOutput::ask_user()`.
    fn ask_user_definition() -> crate::tools::ToolDefinition {
        crate::tools::ToolDefinition {
            name: "ask_user".to_string(),
            description: "Ask the user a clarifying question when you need more information \
                to complete the task. Use this when the request is ambiguous, missing \
                key details, or when you need the user to choose between alternatives. \
                The user's answer will be returned as the tool result."
                .to_string(),
            parameters: serde_json::json!({
                "type": "object",
                "properties": {
                    "question": {
                        "type": "string",
                        "description": "The question to ask the user. Be specific and concise."
                    }
                },
                "required": ["question"]
            }),
        }
    }

    /// Append the `ask_user` tool to a list of tool definitions.
    fn with_ask_user(mut defs: Vec<crate::tools::ToolDefinition>) -> Vec<crate::tools::ToolDefinition> {
        defs.push(Self::ask_user_definition());
        defs
    }

    /// Inject a pipeline execution summary into the main conversation so
    /// follow-up messages can reference what was just done.
    fn inject_pipeline_context(&mut self, task: &str, result: &str) {
        let truncated_result = crate::ui::truncate_str(result, 2000);
        let summary = format!(
            "[Pipeline completed] Task: {}\n\nResult summary:\n{}",
            crate::ui::truncate_str(task, 500),
            truncated_result
        );
        // Add as a user→assistant exchange so the conversation has context
        self.conversation.add_message(Message::user(task));
        self.conversation.add_message(Message::assistant(vec![
            ContentBlock::Text { text: summary },
        ]));
    }

    /// Generate a brief explanation of what a tool is about to do and answer
    /// the user's question. Uses a lightweight LLM call (no tools).
    async fn explain_tool_action(
        &self,
        tool_name: &str,
        tool_input: &serde_json::Value,
        user_question: &str,
    ) -> String {
        let prompt = format!(
            "The AI assistant is about to execute the following tool action:\n\
             Tool: {}\n\
             Parameters: {}\n\n\
             The user asked: {}\n\n\
             Please briefly explain what this tool action will do and answer the user's question. \
             Keep your answer concise (2-4 sentences). Answer in the same language as the user's question.",
            tool_name,
            serde_json::to_string_pretty(tool_input).unwrap_or_default(),
            user_question
        );

        let mut explain_conv = Conversation::new(&self.project_dir);
        explain_conv.system_prompt =
            "You are a helpful assistant explaining tool actions to the user. Be concise."
                .to_string();
        explain_conv.add_message(Message::user(&prompt));

        match self.call_llm_with_retry(&explain_conv, &[]).await {
            Ok(response) => {
                let text: String = response
                    .content
                    .iter()
                    .filter_map(|b| {
                        if let ContentBlock::Text { text } = b {
                            Some(text.as_str())
                        } else {
                            None
                        }
                    })
                    .collect();
                text
            }
            Err(e) => format!("(Failed to generate explanation: {})", e),
        }
    }

    /// Process a user message and return the final text response.
    /// This handles the full agent loop: send message → receive response →
    /// if tool use → execute tools → send results → repeat until done.
    pub async fn process_message(&mut self, user_input: &str) -> Result<String> {
        // ── Adaptive routing ─────────────────────────────────────────────
        let mode = self.resolve_execution_mode(user_input).await;

        match mode {
            crate::router::ExecutionMode::FullPipeline => {
                let result = crate::pipeline::PipelineRunner::run(self, user_input).await?;
                self.inject_pipeline_context(user_input, &result);
                return Ok(result);
            }
            crate::router::ExecutionMode::PlanAndExecute => {
                let result = crate::pipeline::PipelineRunner::run_plan_and_execute(self, user_input).await?;
                self.inject_pipeline_context(user_input, &result);
                return Ok(result);
            }
            crate::router::ExecutionMode::BasicLoop => {
                // Fall through to the basic loop below
            }
        }

        // Add user message
        self.conversation.add_message(Message::user(user_input));

        // Check context window before sending
        self.check_and_manage_context().await;

        let tool_defs = Self::with_ask_user(self.tool_executor.definitions());
        let mut iterations = 0;
        let max_iterations = self.config.max_tool_iterations;

        loop {
            // Check for Ctrl-C interrupt between iterations
            if is_interrupted() {
                self.output.on_warning("Interrupted by user.");
                break;
            }

            // Drain any pending service push notifications so they are displayed
            // at a safe point (not mid-streaming).
            self.drain_service_events();

            iterations += 1;
            if iterations > max_iterations {
                self.output.on_warning(&format!(
                    "Reached maximum tool iterations ({}). Stopping.",
                    max_iterations
                ));
                break;
            }

            // Safety net: fix any orphaned tool_use/tool_result blocks
            // before calling the API.  Truncation or panics can leave the
            // conversation in a state that violates Anthropic's requirement
            // that every tool_use is followed by a tool_result.
            context::ensure_tool_pair_integrity(&mut self.conversation.messages);

            // Send to LLM with automatic retry for transient errors
            let response = self.call_llm_with_retry(&self.conversation, &tool_defs).await?;

            // Track token usage
            if let Some(ref usage) = response.usage {
                self.track_tokens("agent", usage);
            }

            // If the user pressed Ctrl-C during streaming, save any partial
            // text that was already printed and stop immediately.
            if is_interrupted() {
                let partial: Vec<ContentBlock> = response
                    .content
                    .into_iter()
                    .filter(|b| matches!(b, ContentBlock::Text { text } if !text.is_empty()))
                    .collect();
                if !partial.is_empty() {
                    self.conversation.add_message(Message::assistant(partial));
                }
                break;
            }

            // Process the response
            let has_tool_use = response
                .content
                .iter()
                .any(|block| matches!(block, ContentBlock::ToolUse { .. }));

            // Add assistant message to conversation
            let assistant_msg = Message::assistant(response.content.clone());
            self.conversation.add_message(assistant_msg);

            // If no tool use, we're done
            if !has_tool_use {
                break;
            }

            // Execute tools (with confirmation for dangerous operations)
            let tool_uses: Vec<_> = response
                .content
                .iter()
                .filter_map(|block| {
                    if let ContentBlock::ToolUse { id, name, input } = block {
                        Some((id.clone(), name.clone(), input.clone()))
                    } else {
                        None
                    }
                })
                .collect();

            for (tool_id, tool_name, tool_input) in tool_uses {
                // Always show what the LLM wants to do BEFORE asking for
                // confirmation, so the user has full context.
                self.output.on_tool_use(&tool_name, &tool_input);

                // ── Virtual tool: ask_user ────────────────────────────────
                if tool_name == "ask_user" {
                    let question = tool_input
                        .get("question")
                        .and_then(|v| v.as_str())
                        .unwrap_or("Could you clarify?");
                    let answer = self.output.ask_user(question);
                    self.conversation.add_message(Message::tool_result(
                        &tool_id,
                        &format!("User's answer: {}", answer),
                        false,
                    ));
                    continue;
                }

                // Check if this tool needs confirmation
                if needs_confirmation(&tool_name, &tool_input) {
                    let action = build_confirm_action(&tool_name, &tool_input);
                    let mut approved = false;
                    loop {
                        let result = self.output.confirm(&action);
                        match result {
                            crate::confirm::ConfirmResult::Yes
                            | crate::confirm::ConfirmResult::AlwaysYes => {
                                approved = true;
                                break;
                            }
                            crate::confirm::ConfirmResult::No => break,
                            crate::confirm::ConfirmResult::Clarify(question) => {
                                // User wants an explanation — ask the LLM
                                let explanation = self
                                    .explain_tool_action(&tool_name, &tool_input, &question)
                                    .await;
                                self.output.on_assistant_text(&explanation);
                                // Loop back to re-prompt
                            }
                        }
                    }
                    if !approved {
                        self.conversation.add_message(Message::tool_result(
                            &tool_id,
                            "User declined to execute this operation.",
                            true,
                        ));
                        continue;
                    }
                }

                // For file-modifying tools, show diff preview
                let result = if matches!(tool_name.as_str(), "edit_file" | "multi_edit_file" | "write_file") {
                    self.execute_with_diff(&tool_name, &tool_input).await
                } else {
                    self.tool_executor.execute(&tool_name, &tool_input).await
                };

                self.output.on_tool_result(&tool_name, &result);

                // Record to persistent memory
                self.record_tool_to_memory(&tool_name, &tool_input, &result);

                // Add tool result to conversation
                self.conversation.add_message(Message::tool_result(
                    &tool_id,
                    &result.output,
                    result.is_error,
                ));

            }

            // Check context window after tool results
            self.check_and_manage_context().await;

            // Check stop reason
            if let Some(ref reason) = response.stop_reason {
                if reason == "end_turn" && !has_tool_use {
                    break;
                }
            }
        }

        // Return the final text response
        let final_text = self
            .conversation
            .messages
            .iter()
            .rev()
            .find(|m| m.role == crate::conversation::Role::Assistant)
            .map(|m| m.text_content())
            .unwrap_or_default();

        Ok(final_text)
    }

    /// Execute a tool with diff preview for file modifications
    async fn execute_with_diff(
        &self,
        tool_name: &str,
        tool_input: &serde_json::Value,
    ) -> crate::tools::ToolResult {
        let path = tool_input
            .get("path")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        // Use sandbox working dir for path resolution (overlay merged dir or project dir)
        let effective_dir = self.sandbox.working_dir();
        let resolved = resolve_tool_path(path, effective_dir);
        let resolved_str = resolved.display().to_string();

        // Sandbox: snapshot the file before modification
        self.sandbox.before_write(&resolved).await;

        // Read old content if file exists
        let old_content = tokio::fs::read_to_string(&resolved_str).await.ok();

        // Execute the tool
        let result = self.tool_executor.execute(tool_name, tool_input).await;

        // If successful, show diff
        if !result.is_error {
            if let Ok(new_content) = tokio::fs::read_to_string(&resolved_str).await {
                match (tool_name, &old_content) {
                    ("edit_file", Some(old)) => {
                        self.output.on_diff(path, old, &new_content);
                    }
                    ("write_file", Some(old)) => {
                        self.output.on_diff(path, old, &new_content);
                    }
                    ("write_file", None) => {
                        self.output.on_diff(path, "", &new_content);
                    }
                    _ => {}
                }
            }
        }

        result
    }

    /// Track token usage for a specific role.
    fn track_tokens(&mut self, role: &str, usage: &crate::llm::Usage) {
        self.total_input_tokens += usage.input_tokens as u64;
        self.total_output_tokens += usage.output_tokens as u64;
        let entry = self.role_token_usage.entry(role.to_string()).or_insert((0, 0));
        entry.0 += usage.input_tokens as u64;
        entry.1 += usage.output_tokens as u64;
    }

    /// Check context window and truncate if needed.
    ///
    /// When truncation is required, attempts an LLM-driven summarization
    /// of the removed messages to preserve reasoning context. Falls back
    /// to a mechanical summary if the LLM call fails.
    async fn check_and_manage_context(&mut self) {
        let status = context::check_context(&self.conversation, &self.config.model);

        if !status.needs_truncation {
            return;
        }

        self.output.on_context_warning(
            status.usage_percent,
            status.estimated_tokens,
            status.max_tokens,
        );

        // Plan what to truncate (without modifying the conversation yet)
        let plan = match context::plan_truncation(&self.conversation, &self.config.model) {
            Some(plan) => plan,
            None => {
                // Not enough messages to truncate meaningfully
                context::truncate_conversation(&mut self.conversation, &self.config.model, &self.project_dir);
                return;
            }
        };

        // Build condensed context from the messages about to be removed
        let truncation_context = context::build_truncation_context(
            &self.conversation.messages[plan.remove_start..plan.remove_end],
        );

        // Try LLM-driven summarization
        let summary = match self.generate_truncation_summary(&truncation_context).await {
            Ok(s) => s,
            Err(e) => {
                tracing::warn!("LLM summarization failed ({}), using mechanical summary", e);
                context::summarize_removed_messages(
                    &self.conversation.messages[plan.remove_start..plan.remove_end],
                )
            }
        };

        context::apply_truncation(&mut self.conversation, &plan, &summary, &self.project_dir);
    }

    /// Use the LLM to generate a narrative summary of truncated messages.
    ///
    /// This produces a much richer summary than the mechanical fallback,
    /// capturing intent, discoveries, and progress rather than just listing
    /// tool names.
    async fn generate_truncation_summary(&mut self, truncation_context: &str) -> Result<String> {
        let prompt = format!(
            r#"The following is a condensed log of a conversation between a user and an AI coding assistant that is about to be removed from context to save space. Generate a concise narrative summary (3-8 sentences) that captures:

1. What the user's goal/task was
2. What actions were taken (files read, edited, commands run)
3. What was discovered or accomplished
4. Any unresolved issues or next steps

Be factual and specific (include file names, function names, error messages). This summary will be injected back into the conversation so the assistant can maintain continuity.

--- CONVERSATION LOG ---
{}
--- END LOG ---

Summary:"#,
            truncation_context
        );

        let mut summary_conv = Conversation::new(&self.project_dir);
        summary_conv.system_prompt =
            "You are a precise technical summarizer. Output only the summary, no extra commentary. \
             Keep it under 200 words.".to_string();
        summary_conv.add_message(Message::user(&prompt));

        // Use the main model (or a "summarizer" role if configured)
        let response = self.call_llm_as_role("summarizer", &summary_conv, &[]).await?;

        if let Some(ref usage) = response.usage {
            self.track_tokens("summarizer", usage);
        }

        let text: String = response
            .content
            .iter()
            .filter_map(|b| {
                if let ContentBlock::Text { text } = b {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n");

        let text = text.trim().to_string();
        if text.is_empty() {
            anyhow::bail!("LLM returned empty summary");
        }

        Ok(text)
    }

    /// Get total token usage.
    pub fn token_usage(&self) -> (u64, u64) {
        (self.total_input_tokens, self.total_output_tokens)
    }

    /// Get per-role token usage breakdown.
    pub fn role_token_usage(&self) -> &HashMap<String, (u64, u64)> {
        &self.role_token_usage
    }

    /// Reset the conversation
    pub fn reset(&mut self) {
        self.conversation.clear();
        self.total_input_tokens = 0;
        self.total_output_tokens = 0;
        self.role_token_usage.clear();
    }

    /// Record a tool action to persistent memory.
    fn record_tool_to_memory(
        &mut self,
        tool_name: &str,
        tool_input: &serde_json::Value,
        result: &crate::tools::ToolResult,
    ) {
        let path = tool_input.get("path").and_then(|v| v.as_str()).unwrap_or("");

        match tool_name {
            "read_file" => {
                if !path.is_empty() {
                    self.memory.touch_file(path, "read");
                    self.memory.log_action(&format!("read {}", path));
                }
            }
            "write_file" => {
                if !path.is_empty() && !result.is_error {
                    let lines = tool_input
                        .get("content")
                        .and_then(|v| v.as_str())
                        .map(|c| c.lines().count())
                        .unwrap_or(0);
                    self.memory.touch_file(path, &format!("written ({} lines)", lines));
                    self.memory.log_action(&format!("wrote {}", path));
                }
            }
            "edit_file" => {
                if !path.is_empty() && !result.is_error {
                    self.memory.touch_file(path, "edited");
                    self.memory.log_action(&format!("edited {}", path));
                }
            }
            "run_command" => {
                if !result.is_error {
                    let cmd = tool_input
                        .get("command")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    let short_cmd = crate::ui::truncate_str(cmd, 60);
                    self.memory.log_action(&format!("ran `{}`", short_cmd));
                }
            }
            "grep_search" => {
                let pattern = tool_input
                    .get("pattern")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                if !pattern.is_empty() {
                    self.memory.log_action(&format!("searched for `{}`", pattern));
                }
                // If a specific path/directory was targeted, record it
                if !path.is_empty() {
                    self.memory.touch_file(path, "searched");
                }
            }
            "file_search" => {
                let pattern = tool_input
                    .get("pattern")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");
                if !pattern.is_empty() {
                    self.memory.log_action(&format!("found files matching `{}`", pattern));
                }
            }
            "list_directory" => {
                let dir = if path.is_empty() { "." } else { path };
                self.memory.log_action(&format!("listed {}", dir));
            }
            "multi_edit_file" => {
                if !path.is_empty() && !result.is_error {
                    let edit_count = tool_input
                        .get("edits")
                        .and_then(|v| v.as_array())
                        .map(|a| a.len())
                        .unwrap_or(0);
                    self.memory.touch_file(path, &format!("multi-edited ({} edits)", edit_count));
                    self.memory.log_action(&format!("multi-edited {} ({} edits)", path, edit_count));
                }
            }
            "batch_read_files" => {
                if let Some(paths) = tool_input.get("paths").and_then(|v| v.as_array()) {
                    for p in paths {
                        if let Some(s) = p.as_str() {
                            self.memory.touch_file(s, "read");
                        }
                    }
                    self.memory.log_action(&format!("batch-read {} files", paths.len()));
                }
            }
            "read_pdf" => {
                if !path.is_empty() {
                    self.memory.touch_file(path, "read (PDF)");
                    self.memory.log_action(&format!("read PDF {}", path));
                }
            }
            "think" => {
                // No memory update for think — it's internal reasoning
            }
            _ => {}
        }

        // Auto-save memory (silent)
        if let Err(e) = self.memory.save() {
            tracing::warn!("Failed to save memory: {}", e);
        }
    }

    /// Save memory to disk (public, for use from CLI)
    #[allow(dead_code)]
    pub fn save_memory(&self) {
        if let Err(e) = self.memory.save() {
            tracing::warn!("Failed to save memory: {}", e);
        }
    }

    /// Generate a plan for the given task without executing it.
    ///
    /// During the planning phase the LLM only has access to **read-only** tools
    /// (read_file, list_directory, grep_search, file_search) so it can explore
    /// the codebase but cannot modify anything.  The resulting plan text is
    /// stored in `self.pending_plan` and returned.
    pub async fn generate_plan(&mut self, task: &str) -> Result<String> {
        // ── Build context sections to inject ─────────────────────────────
        // 1. Project summary (from .agent/summary.md)
        let summary_section = crate::summary::load(&self.project_dir)
            .map(|s| format!("\n\n## Project Summary\n{}", s))
            .unwrap_or_default();

        // 2. Memory: project knowledge + file map
        let memory = crate::memory::Memory::load(&self.project_dir);
        let mut memory_section = String::new();
        if !memory.knowledge.is_empty() || !memory.file_map.is_empty() {
            memory_section.push_str("\n\n## Project Knowledge (from memory)");
            for k in &memory.knowledge {
                memory_section.push_str(&format!("\n- {}", k));
            }
            if !memory.file_map.is_empty() {
                memory_section.push_str("\n\n## Known Important Files");
                for (path, desc) in &memory.file_map {
                    memory_section.push_str(&format!("\n- {}: {}", path, desc));
                }
            }
        }

        // 3. Recent conversation history (last 6 turns = 3 user+assistant pairs)
        //    Gives planner context on what has already been discussed / done.
        let history_section = {
            let msgs = &self.conversation.messages;
            let recent: Vec<_> = msgs.iter().rev().take(6).collect();
            if recent.is_empty() {
                String::new()
            } else {
                let mut buf = String::from("\n\n## Recent Conversation History (most recent first)");
                for msg in recent {
                    let role = match msg.role {
                        crate::conversation::Role::User      => "User",
                        crate::conversation::Role::Assistant => "Assistant",
                        crate::conversation::Role::System    => continue,
                    };
                    // Only include Text blocks to keep this concise
                    let text: String = msg.content.iter()
                        .filter_map(|b| if let ContentBlock::Text { text } = b { Some(text.as_str()) } else { None })
                        .collect::<Vec<_>>()
                        .join(" ");
                    if !text.trim().is_empty() {
                        let preview = crate::ui::truncate_str(&text, 400);
                        buf.push_str(&format!("\n[{}]: {}", role, preview.trim()));
                    }
                }
                buf
            }
        };

        let planning_prompt = format!(
            r#"The user wants to accomplish the following task:

{}
{}{}{}

Please analyze the task carefully in the context above. You may use the read-only tools available to explore the codebase and gather any additional information you need.
You also have access to `run_command` — use it ONLY for read-only exploration commands such as:
  git status, git log, git diff, git show, git branch, git remote -v,
  find, cat, ls, wc, head, tail, cargo metadata, etc.
Do NOT run any command that mutates state (no commits, pushes, file writes, installs, builds).

IMPORTANT: If the task is ambiguous, missing key details, or requires user decisions (e.g. choice of approach, naming, scope), use the `ask_user` tool to ask clarifying questions BEFORE producing the plan. Do NOT guess — ask.

Then output a detailed, numbered step-by-step plan describing exactly what changes and actions are needed. For each step, specify:
1. What action to take (create/edit/delete file, run command, etc.)
2. Which file(s) are involved
3. A brief description of the change
4. Any dependencies on other steps

⚠️  Do NOT execute any modifications — only produce the plan."#,
            task, summary_section, memory_section, history_section
        );

        // Use a separate conversation branch for planning so the main
        // conversation is not polluted.
        let mut plan_conversation = Conversation::new(&self.project_dir);
        plan_conversation.system_prompt = format!(
            "{}\n\nYou are in PLANNING MODE. \
             You can use the provided read-only tools to explore the project, \
             and the `ask_user` tool to ask clarifying questions. \
             You also have access to `run_command`, but you MUST only use it for \
             purely read-only shell / git commands that do not mutate any state, \
             such as: git status, git log, git diff, git show, git branch, \
             git remote -v, find, cat, ls, wc, head, tail, echo, env, cargo metadata. \
             NEVER run commands that write files, make commits, push, install packages, \
             build, or modify any state. \
             Your final output MUST be a clear numbered plan. \
             Do NOT execute any modifications.",
            self.conversation.system_prompt
        );
        plan_conversation.add_message(Message::user(&planning_prompt));

        let readonly_tools = Self::with_ask_user(self.tool_executor.readonly_definitions());

        // Use the same iteration budget as the main loop so planning never gets
        // silently truncated on complex projects.
        let max_iters = self.config.max_tool_iterations;
        let mut plan_text = String::new();
        let mut exhausted = true;

        for _ in 0..max_iters {
            // Use the planner role model if configured
            let response = self.call_llm_as_role("planner", &plan_conversation, &readonly_tools).await?;

            // Track tokens
            if let Some(ref usage) = response.usage {
                self.track_tokens("planner", usage);
            }

            let has_tool_use = response.content.iter().any(|b| matches!(b, ContentBlock::ToolUse { .. }));

            plan_conversation.add_message(Message::assistant(response.content.clone()));

            if !has_tool_use {
                // LLM finished naturally — collect the plan text.
                for block in &response.content {
                    if let ContentBlock::Text { text } = block {
                        plan_text.push_str(text);
                    }
                }
                exhausted = false;
                break;
            }

            // Execute only the read-only tools
            let tool_uses: Vec<_> = response
                .content
                .iter()
                .filter_map(|block| {
                    if let ContentBlock::ToolUse { id, name, input } = block {
                        Some((id.clone(), name.clone(), input.clone()))
                    } else {
                        None
                    }
                })
                .collect();

            for (tool_id, tool_name, tool_input) in tool_uses {
                self.output.on_tool_use(&tool_name, &tool_input);

                // ── Virtual tool: ask_user ────────────────────────────
                if tool_name == "ask_user" {
                    let question = tool_input
                        .get("question")
                        .and_then(|v| v.as_str())
                        .unwrap_or("Could you clarify?");
                    let answer = self.output.ask_user(question);
                    plan_conversation.add_message(Message::tool_result(
                        &tool_id,
                        &format!("User's answer: {}", answer),
                        false,
                    ));
                    continue;
                }

                let result = self.tool_executor.execute(&tool_name, &tool_input).await;
                self.output.on_tool_result(&tool_name, &result);
                plan_conversation.add_message(Message::tool_result(
                    &tool_id,
                    &result.output,
                    result.is_error,
                ));
            }
        }

        // If the loop exhausted all iterations without the LLM stopping naturally,
        // force one final call with no tools available so it has to write the plan.
        if exhausted {
            self.output.on_assistant_text(
                "\n[Exploration limit reached — consolidating findings into a plan…]\n"
            );
            plan_conversation.add_message(Message::user(
                "You have finished exploring. Now write the complete, detailed, numbered \
                 step-by-step plan based on everything you have discovered. \
                 Do not call any more tools — output only the plan text."
            ));
            let final_response = self.call_llm_as_role("planner", &plan_conversation, &[]).await?;
            if let Some(ref usage) = final_response.usage {
                self.track_tokens("planner", usage);
            }
            for block in &final_response.content {
                if let ContentBlock::Text { text } = block {
                    plan_text.push_str(text);
                }
            }
        }

        let plan_text = plan_text.trim().to_string();
        if plan_text.is_empty() {
            anyhow::bail!("LLM returned an empty plan");
        }

        self.pending_plan = Some(plan_text.clone());
        Ok(plan_text)
    }

    /// Execute a previously generated plan.
    ///
    /// The plan is injected into the main conversation as context, and the full
    /// set of tools is made available so the LLM can carry out each step.
    /// Uses the "executor" role model if configured in models.toml.
    pub async fn execute_plan(&mut self, plan: &str) -> Result<String> {
        let exec_prompt = format!(
            r#"You previously created the following plan. Now execute it step by step.
After completing each step, briefly report what was done before moving on to the next step.
If a step fails, explain the error and try to recover.

--- PLAN ---
{}
--- END PLAN ---

Begin execution now."#,
            plan
        );

        self.pending_plan = None;

        // Phase 3 (pipeline.rs) will run a dedicated executor loop with its own config.
        // For now, process_message will show the active model via on_role_header.
        self.process_message(&exec_prompt).await
    }

    /// Run a single pipeline stage with a role-specific model.
    ///
    /// Creates a fresh `Conversation` (does not touch `self.conversation`),
    /// uses `call_llm_as_role` so the role's model is shown in the UI,
    /// and runs the full tool loop until the LLM stops requesting tools.
    ///
    /// `readonly_only` restricts the available tools to read-only operations
    /// (used for the Checker stage).
    pub async fn run_pipeline_stage(
        &mut self,
        role: &str,
        initial_message: &str,
        readonly_only: bool,
    ) -> Result<String> {
        let mut stage_conv = Conversation::new(&self.project_dir);
        stage_conv.system_prompt = self.conversation.system_prompt.clone();
        stage_conv.add_message(Message::user(initial_message));

        let tool_defs = if readonly_only {
            Self::with_ask_user(self.tool_executor.readonly_definitions())
        } else {
            Self::with_ask_user(self.tool_executor.definitions())
        };

        let max_iterations = self.config.max_tool_iterations;
        let mut final_text = String::new();

        for _ in 0..max_iterations {
            if is_interrupted() {
                self.output.on_warning("Interrupted by user.");
                break;
            }

            self.drain_service_events();

            // ── Mid-execution guidance (Ctrl-\) ──────────────────────────────
            // Append user guidance to the system prompt so the LLM sees it on
            // the next call without violating the message turn structure.
            if is_guidance_requested() {
                clear_guidance();
                if let Some(text) = self.output.inject_guidance() {
                    stage_conv.system_prompt.push_str(&format!(
                        "\n\n[⚡ USER GUIDANCE]: {}",
                        text
                    ));
                    self.output.on_warning(&format!("💡 Guidance injected into executor context."));
                }
            }

            context::ensure_tool_pair_integrity(&mut stage_conv.messages);

            let response = self.call_llm_as_role(role, &stage_conv, &tool_defs).await?;

            if let Some(ref usage) = response.usage {
                self.track_tokens(role, usage);
            }

            // If the user pressed Ctrl-C during streaming, stop immediately.
            if is_interrupted() {
                break;
            }

            // Collect final text; print for non-streaming providers
            for block in &response.content {
                if let ContentBlock::Text { text } = block {
                    if !text.is_empty() {
                        final_text = text.clone();
                        let role_cfg = self.role_configs.get(role).unwrap_or(&self.config);
                        if role_cfg.provider != Provider::Anthropic {
                            self.output.on_assistant_text(text);
                        }
                    }
                }
            }

            let has_tool_use = response
                .content
                .iter()
                .any(|b| matches!(b, ContentBlock::ToolUse { .. }));
            stage_conv.add_message(Message::assistant(response.content.clone()));

            if !has_tool_use {
                break;
            }

            let tool_uses: Vec<_> = response
                .content
                .iter()
                .filter_map(|b| {
                    if let ContentBlock::ToolUse { id, name, input } = b {
                        Some((id.clone(), name.clone(), input.clone()))
                    } else {
                        None
                    }
                })
                .collect();

            for (tool_id, tool_name, tool_input) in tool_uses {
                self.output.on_tool_use(&tool_name, &tool_input);

                // ── Virtual tool: ask_user ────────────────────────────
                if tool_name == "ask_user" {
                    let question = tool_input
                        .get("question")
                        .and_then(|v| v.as_str())
                        .unwrap_or("Could you clarify?");
                    let answer = self.output.ask_user(question);
                    stage_conv.add_message(Message::tool_result(
                        &tool_id,
                        &format!("User's answer: {}", answer),
                        false,
                    ));
                    continue;
                }

                if !readonly_only && needs_confirmation(&tool_name, &tool_input) {
                    let action = build_confirm_action(&tool_name, &tool_input);
                    let mut approved = false;
                    loop {
                        let result = self.output.confirm(&action);
                        match result {
                            crate::confirm::ConfirmResult::Yes
                            | crate::confirm::ConfirmResult::AlwaysYes => {
                                approved = true;
                                break;
                            }
                            crate::confirm::ConfirmResult::No => break,
                            crate::confirm::ConfirmResult::Clarify(question) => {
                                let explanation = self
                                    .explain_tool_action(&tool_name, &tool_input, &question)
                                    .await;
                                self.output.on_assistant_text(&explanation);
                            }
                        }
                    }
                    if !approved {
                        stage_conv.add_message(Message::tool_result(
                            &tool_id,
                            "User declined to execute this operation.",
                            true,
                        ));
                        continue;
                    }
                }

                let result = if matches!(
                    tool_name.as_str(),
                    "edit_file" | "multi_edit_file" | "write_file"
                ) {
                    self.execute_with_diff(&tool_name, &tool_input).await
                } else {
                    self.tool_executor.execute(&tool_name, &tool_input).await
                };

                self.output.on_tool_result(&tool_name, &result);
                self.record_tool_to_memory(&tool_name, &tool_input, &result);
                stage_conv.add_message(Message::tool_result(
                    &tool_id,
                    &result.output,
                    result.is_error,
                ));
            }

            // Manage context for the stage conversation so large tool
            // outputs (e.g. reading 470-line files) don't push us over
            // the window limit and cause premature loop termination.
            let status = context::check_context(&stage_conv, &self.config.model);
            if status.needs_truncation {
                context::truncate_conversation(&mut stage_conv, &self.config.model, &self.project_dir);
            }
        }

        Ok(final_text)
    }

    /// Scan the project directory and use the LLM to generate a project summary.
    /// The summary is saved to `.agent/summary.md` so subsequent sessions skip this step.
    pub async fn generate_project_summary(&mut self) -> Result<String> {
        let cwd = self.project_dir.clone();

        // Step 1: Scan directory structure (depth 2)
        let dir_result = self
            .tool_executor
            .execute(
                "list_directory",
                &serde_json::json!({ "path": ".", "recursive": true }),
            )
            .await;
        let dir_tree = if dir_result.is_error {
            "(failed to list directory)".to_string()
        } else {
            dir_result.output
        };

        // Step 2: Try to read key project files for extra context
        let key_files = [
            "README.md",
            "Cargo.toml",
            "package.json",
            "Makefile",
            "CMakeLists.txt",
            "pyproject.toml",
            "go.mod",
            "AGENT.md",
        ];
        let mut file_contents = Vec::new();
        for filename in &key_files {
            let path = cwd.join(filename);
            if path.exists() {
                let read_result = self
                    .tool_executor
                    .execute(
                        "read_file",
                        &serde_json::json!({
                            "path": filename,
                            "max_lines": 200
                        }),
                    )
                    .await;
                if !read_result.is_error {
                    file_contents.push(format!("--- {} ---\n{}", filename, read_result.output));
                }
            }
        }

        let files_context = if file_contents.is_empty() {
            String::new()
        } else {
            format!("\n\nKey file contents:\n{}", file_contents.join("\n\n"))
        };

        // Step 3: Build a one-shot prompt to generate the summary
        let prompt = format!(
            r#"Please analyze this project and generate a concise project summary (in the same language as any README or docs found). The summary should include:

1. **Project name and purpose** (1-2 sentences)
2. **Tech stack** (language, frameworks, key dependencies)
3. **Directory structure overview** (major modules/components)
4. **Build & run commands** (if discoverable)
5. **Key conventions** (coding style, patterns observed)

Keep it compact (under 30 lines). This summary will be stored and reused across sessions so the AI agent can quickly understand the project without re-reading everything.

Project directory: {}

Directory tree:
{}
{}"#,
            cwd.display(),
            dir_tree,
            files_context
        );

        // Step 4: Send to LLM using a temporary conversation (don't pollute main one)
        let mut summary_conversation = Conversation::new(&self.project_dir);
        summary_conversation.system_prompt =
            "You are a helpful assistant that generates concise project summaries. \
             Output only the summary content, no extra commentary."
                .to_string();
        summary_conversation.add_message(Message::user(&prompt));

        let response = self.call_llm_with_retry(&summary_conversation, &[]).await?;

        // Track token usage
        if let Some(ref usage) = response.usage {
            self.track_tokens("summary", usage);
        }

        // Extract text
        let summary_text: String = response
            .content
            .iter()
            .filter_map(|block| {
                if let ContentBlock::Text { text } = block {
                    Some(text.as_str())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>()
            .join("\n");

        let summary_text = summary_text.trim().to_string();
        if summary_text.is_empty() {
            anyhow::bail!("LLM returned an empty project summary");
        }

        // Step 5: Save to .agent/summary.md
        crate::summary::save(&cwd, &summary_text)?;

        // Step 6: Inject into current session's system prompt
        self.conversation
            .system_prompt
            .push_str(&crate::summary::to_system_prompt_section(&summary_text));

        Ok(summary_text)
    }
}

/// Resolve a path (relative to project_dir or absolute)
fn resolve_tool_path(path: &str, project_dir: &std::path::Path) -> std::path::PathBuf {
    let p = std::path::Path::new(path);
    if p.is_absolute() {
        p.to_path_buf()
    } else {
        project_dir.join(p)
    }
}

/// Check if a tool action needs user confirmation
fn needs_confirmation(tool_name: &str, _input: &serde_json::Value) -> bool {
    match tool_name {
        "write_file" | "edit_file" | "multi_edit_file" => true,
        "run_command" => {
            // All run_command executions need confirmation because they can be dangerous
            true
        }
        _ => false,
    }
}

/// Build a ConfirmAction from tool name and input
fn build_confirm_action(tool_name: &str, input: &serde_json::Value) -> ConfirmAction {
    match tool_name {
        "write_file" => {
            let path = input
                .get("path")
                .and_then(|v| v.as_str())
                .unwrap_or("<unknown>")
                .to_string();
            let lines = input
                .get("content")
                .and_then(|v| v.as_str())
                .map(|c| c.lines().count())
                .unwrap_or(0);
            ConfirmAction::WriteFile { path, lines }
        }
        "edit_file" | "multi_edit_file" => {
            let path = input
                .get("path")
                .and_then(|v| v.as_str())
                .unwrap_or("<unknown>")
                .to_string();
            ConfirmAction::EditFile { path }
        }
        "run_command" => {
            let command = input
                .get("command")
                .and_then(|v| v.as_str())
                .unwrap_or("<unknown>")
                .to_string();
            ConfirmAction::RunCommand { command }
        }
        _ => ConfirmAction::RunCommand {
            command: format!("{}: {}", tool_name, input),
        },
    }
}
/// Build a per-role Config map from the loaded models.toml.
///
/// For every entry in `[roles]` that references a valid model alias,
/// we pre-build a `Config` so callers can just do `role_configs["planner"]`
/// without repeating resolution logic.
fn build_role_configs(
    base: &Config,
    models_cfg: &model_manager::ModelsConfig,
) -> HashMap<String, Config> {
    let mut map = HashMap::new();
    for (role_name, role_cfg) in &models_cfg.roles {
        let config = base.for_role(role_name, models_cfg);
        // If system_prompt is set inline, we store it in the role entry but
        // the actual prompt injection happens in pipeline.rs / generate_plan.
        // Here we only care about which model/provider/key to call.
        let _ = &role_cfg.system_prompt; // acknowledged, used later
        map.insert(role_name.clone(), config);
    }
    map
}